import json
import os

# 1. 띄어쓰기 교정 로직 복구
PHRASES_TO_FIX = {
    "takecareof": "take care of", "apartfrom": "apart from", "farfrom": "far from",
    "asto": "as to", "byfar": "by far", "callfor": "call for",
    "comeacross": "come across", "comeupwith": "come up with", "consistof": "consist of",
    "makeup": "make up", "endup": "end up", "freeof": "free of",
    "getridof": "get rid of", "handin": "hand in", "athand": "at hand",
    "inadvance": "in advance", "inadditionto": "in addition to", "intermsof": "in terms of",
    "regardlessof": "regardless of", "passaway": "pass away", "bringabout": "bring about"
}

def clean_word(w):
    w = w.lower().replace(" ", "")
    return PHRASES_TO_FIX.get(w, w)

# 2. 임시 뜻 DB (실제로는 방대한 DB가 필요함)
MEANING_DB = {
    "religion": ["종교"], "border": ["국경", "경계"],    "spread": ["퍼뜨리다", "확산되다"],    "escape": ["달아나다", "탈출하다"],    "common": ["공통의", "흔한"],    "remain": ["남다", "여전히 ~이다"],    "punish": ["처벌하다"],    "fee": ["요금", "수수료"],    "familiar": ["익숙한", "친숙한"],    "volunteer": ["자원봉사자", "자원하다"],    "square": ["정사각형", "광장"],    "steal": ["훔치다"],    "attack": ["공격하다"],    "represent": ["대표하다", "나타내다"],    "arrow": ["화살"],    "shoot": ["쏘다", "촬영하다"],    "matter": ["문제", "중요하다"],    "shake": ["흔들다"],    "ruin": ["망치다", "유적"],    "result": ["결과"],    "bless": ["축복하다"],    "exist": ["존재하다"],    "medicine": ["약", "의학"],    "pack": ["짐을 싸다", "꾸러미"],    "repeat": ["반복하다"],    "perform": ["수행하다", "공연하다"],    "popular": ["인기 있는"],    "regular": ["규칙적인", "정기적인"],    "seldom": ["좀처럼 ~않는"],    "president": ["대통령", "회장"],    "international": ["국제의"],    "overcome": ["극복하다"],    "destroy": ["파괴하다"],    "reply": ["대답하다", "답장"],    "treasure": ["보물"],    "favor": ["호의", "부탁"],    "grade": ["학년", "성적"],    "trust": ["신뢰하다", "믿음"],    "term": ["용어", "기간"],    "spell": ["철자를 쓰다"],    "regret": ["후회하다"],    "suggest": ["제안하다", "암시하다"],    "recognize": ["알아보다", "인정하다"],    "balance": ["균형"],    "notice": ["알아차리다", "통지"],    "realize": ["깨닫다", "실현하다"],    "admire": ["존경하다", "감탄하다"],    "needle": ["바늘"],    "tray": ["쟁반"],    "role": ["역할"],    "pride": ["자부심", "자존심"],    "tie": ["묶다", "넥타이"],    "repair": ["수리하다"],    "soap": ["비누"],    "normal": ["보통의", "정상적인"],    "smooth": ["매끄러운"],    "trade": ["무역", "거래하다"],    "benefit": ["이익", "혜택"],    "crop": ["농작물"],    "gather": ["모으다", "모이다"],    "stadium": ["경기장"],    "incredible": ["믿기 힘든", "굉장한"],    "coach": ["코치", "지도하다"],    "strike": ["치다", "파업"],    "desire": ["욕구", "바라다"],    "able": ["~할 수 있는"],    "pain": ["통증", "고통"],    "spend": ["소비하다", "보내다"],    "belong": ["~에 속하다"],    "usual": ["보통의", "평소의"],    "neighbor": ["이웃"],    "practice": ["연습", "실행"],    "false": ["가짜의", "틀린"],    "perfect": ["완벽한"],    "scene": ["장면", "현장"],    "reach": ["도달하다", "손을 뻗다"],    "judge": ["판단하다", "판사"],    "conversation": ["대화"],    "shoulder": ["어깨"],    "mistake": ["실수"],    "enemy": ["적"],    "cheer": ["응원하다"],    "continue": ["계속하다"],    "garbage": ["쓰레기"],    "possible": ["가능한"],    "foreign": ["외국의"],    "period": ["기간", "시대"],    "except": ["~을 제외하고"],    "laugh": ["웃다"],    "instead": ["대신에"],    "major": ["주요한", "전공"],    "round": ["둥근"],    "aim": ["목표", "겨냥하다"],    "nowadays": ["요즘에는"],    "secret": ["비밀"],    "disease": ["질병"],    "miracle": ["기적"],    "protein": ["단백질"],    "patient": ["환자", "인내심 있는"],    "prefer": ["선호하다"],    "avoid": ["피하다"],    "prevent": ["예방하다", "방지하다"],    "fault": ["잘못", "결점"],    "sudden": ["갑작스러운"],    "trouble": ["문제", "곤란"],    "aid": ["도움", "원조"],    "portrait": ["초상화"],    "whole": ["전체의"],    "individual": ["개인", "개별의"],    "influence": ["영향", "영향을 미치다"],    "master": ["숙달하다", "주인"],    "advance": ["진보", "전진"],    "develop": ["개발하다", "발전시키다"],    "nest": ["둥지"],    "match": ["경기", "어울리다"],    "chest": ["가슴", "상자"],    "demand": ["요구하다", "수요"],    "wealth": ["부", "재산"],    "account": ["계좌", "설명"],    "serve": ["제공하다", "봉사하다"],    "grave": ["무덤", "심각한"],    "explain": ["설명하다"],    "achieve": ["성취하다"],    "remove": ["제거하다"],    "dictionary": ["사전"],    "receive": ["받다"],    "smoke": ["연기", "담배 피우다"],    "meal": ["식사"],    "social": ["사회적인"],    "bark": ["짖다", "나무껍질"],    "grammar": ["문법"],    "trunk": ["줄기", "코끼리 코", "트렁크"],    "reason": ["이유", "이성"],    "health": ["건강"],    "earn": ["벌다"],    "contain": ["포함하다"],    "solve": ["해결하다"],    "necessary": ["필요한"],    "hide": ["숨기다"],    "raise": ["올리다", "기르다"],    "desert": ["사막", "버리다"],    "past": ["과거", "지나간"],    "island": ["섬"],    "courage": ["용기"],    "metal": ["금속"],    "research": ["연구"],    "serious": ["심각한", "진지한"],    "invent": ["발명하다"],    "station": ["역", "소"],    "material": ["재료", "물질"],    "alive": ["살아있는"],    "straw": ["빨대", "짚"],    "perhaps": ["아마도"],    "uniform": ["제복", "균일한"],    "follow": ["따르다"],    "attend": ["참석하다"],    "opportunity": ["기회"],    "astronaut": ["우주비행사"],    "rise": ["오르다", "상승"],    "universe": ["우주"],    "support": ["지지하다", "부양하다"],    "deliver": ["배달하다"],    "language": ["언어"],    "vocabulary": ["어휘"],    "magazine": ["잡지"],    "article": ["기사", "물품"],    "several": ["몇몇의"],    "village": ["마을"],    "reflect": ["반사하다", "반영하다"],    "source": ["근원", "출처"],    "purpose": ["목적"],    "various": ["다양한"],    "discover": ["발견하다"],    "element": ["요소"],    "steam": ["증기"],    "express": ["표현하다", "급행의"],    "share": ["공유하다", "몫"],    "symbol": ["상징"],    "special": ["특별한"],    "stomach": ["위", "복부"],    "blank": ["빈칸", "멍한"],    "effort": ["노력"],    "empty": ["비어 있는"],    "search": ["검색하다", "찾다"],    "doubt": ["의심하다"],    "moment": ["순간"],    "increase": ["증가하다"],    "decrease": ["감소하다"],    "valuable": ["가치 있는", "귀중한"],    "journey": ["여정", "여행"],    "formal": ["격식을 갖춘", "공식적인"],    "soldier": ["군인"],    "prepare": ["준비하다"],    "information": ["정보"],    "organize": ["조직하다", "정리하다"],    "method": ["방법"],    "convenient": ["편리한"],    "traffic": ["교통"],    "agency": ["대리점", "기관"],    "distance": ["거리"],    "path": ["길", "통로"],    "tunnel": ["터널"],    "signal": ["신호"],    "ashamed": ["부끄러워하는"],    "figure": ["인물", "숫자", "모양"],    "storm": ["폭풍"],    "shine": ["빛나다"],    "observe": ["관찰하다", "준수하다"],    "polite": ["공손한"],    "label": ["라벨", "꼬리표"],    "prove": ["증명하다"],    "confuse": ["혼란스럽게 하다"],    "eager": ["열망하는"],    "amount": ["양"],    "modern": ["현대의"],    "sail": ["항해하다"],    "press": ["누르다", "언론"],    "appear": ["나타나다", "~인 것 같다"],    "complain": ["불평하다"],    "purse": ["지갑"],    "promise": ["약속하다"],    "silent": ["침묵하는"],    "happen": ["발생하다"],    "excuse": ["변명", "용서하다"],    "correct": ["맞는", "교정하다"],    "inform": ["알리다"],    "therefore": ["그러므로"],    "shape": ["모양", "형성하다"],    "leave": ["떠나다", "남겨두다"],    "grain": ["곡물"],    "produce": ["생산하다"],    "loyal": ["충성스러운"],    "manner": ["방식", "예의"],    "university": ["대학교"],    "experience": ["경험"],    "author": ["작가"],    "report": ["보고서", "보도하다"],    "effect": ["효과", "영향"],    "vacation": ["휴가"],    "price": ["가격"],    "poem": ["시"],    "prison": ["교도소"],    "character": ["성격", "등장인물"],    "hike": ["도보 여행하다"],    "pull": ["당기다"],    "count": ["세다", "중요하다"],    "palace": ["궁전"],    "hurry": ["서두르다"],    "tea": ["차"],    "curly": ["곱슬곱슬한"],    "sale": ["판매"],    "wonderful": ["멋진"],    "funny": ["재미있는"],    "copy": ["복사하다", "사본"],    "brave": ["용감한"],    "country": ["나라", "시골"],    "subject": ["과목", "주제"],    "apply": ["지원하다", "적용하다"],    "recycle": ["재활용하다"],    "problem": ["문제"],    "difficult": ["어려운"],    "bookstore": ["서점"],    "wash": ["씻다"],    "natural": ["자연의", "당연한"],    "culture": ["문화"],    "exercise": ["운동", "연습"],    "later": ["나중에"],    "wolf": ["늑대"],    "slide": ["미끄러지다"],    "super": ["최고의"],    "jewel": ["보석"],    "mild": ["부드러운", "온화한"],    "maybe": ["아마도"],    "liberty": ["자유"],    "collect": ["수집하다"],    "proud": ["자랑스러운"],    "feed": ["먹이를 주다"],    "agree": ["동의하다"],    "calendar": ["달력"],    "compare": ["비교하다"],    "surf": ["파도타기를 하다"],    "playground": ["운동장", "놀이터"],    "ride": ["타다"],    "outcome": ["결과"],    "favorite": ["가장 좋아하는"],    "pill": ["알약"],    "spicy": ["매운"],    "main": ["주요한"],    "ocean": ["대양", "바다"],    "wise": ["지혜로운"],    "bored": ["지루해하는"],    "chore": ["허드렛일", "잡일"],    "travel": ["여행하다"],    "waste": ["낭비하다", "쓰레기"],    "begin": ["시작하다"],    "navy": ["해군"],    "boom": ["호황", "쿵 하고 울리는 소리"],    "child": ["아이"],    "thermometer": ["온도계"],    "progress": ["진보", "발전"],    "elect": ["선출하다"],    "improve": ["개선하다", "향상시키다"],    "spirit": ["정신", "영혼"],    "labor": ["노동"],    "shadow": ["그림자"],    "annoy": ["짜증나게 하다"],    "include": ["포함하다"],    "weapon": ["무기"],    "immune": ["면역의"],    "vomit": ["토하다"],    "remind": ["상기시키다"],    "wage": ["임금"],    "protect": ["보호하다"],    "suffer": ["고통받다"],    "income": ["수입"],    "attempt": ["시도하다"],    "found": ["설립하다", "기초를 두다"],    "supply": ["공급하다"],    "principal": ["교장", "주요한"],    "wrinkle": ["주름"],    "scale": ["규모", "저울"],    "obtain": ["얻다", "획득하다"],    "affect": ["영향을 미치다"],    "average": ["평균"],    "crisis": ["위기"],    "citizen": ["시민"],    "fellow": ["동료"],    "suppose": ["가정하다", "생각하다"],    "passenger": ["승객"],    "emotion": ["감정"],    "obey": ["복종하다"],    "claim": ["주장하다", "요구하다"],    "involve": ["포함하다", "관련시키다"],    "quality": ["품질", "특성"],    "provide": ["제공하다"],    "physical": ["신체적인", "물리적인"],    "measure": ["측정하다", "조치"],    "overweight": ["과체중의"],    "particular": ["특정한", "까다로운"],    "unless": ["~하지 않는다면"],    "otherwise": ["그렇지 않으면"],    "rush": ["서두르다"],    "position": ["위치", "입장"],    "entertain": ["즐겁게 하다"],    "terrible": ["끔찍한"],    "industry": ["산업", "근면"],    "refrigerator": ["냉장고"],    "crime": ["범죄"],    "range": ["범위"],    "mention": ["언급하다"],    "settle": ["정착하다", "해결하다"],    "blame": ["비난하다", "탓으로 돌리다"],    "refuse": ["거절하다"],    "pregnant": ["임신한"],    "factor": ["요인"],    "require": ["요구하다", "필요로 하다"],    "edge": ["가장자리", "날"],    "dozen": ["12개", "다수"],    "charge": ["요금", "책임", "충전하다"],    "symptom": ["증상"],    "merchant": ["상인"],    "continent": ["대륙"],    "replace": ["교체하다", "대신하다"],    "consist": ["~로 구성되다"],    "especially": ["특히"],    "command": ["명령하다"],    "complete": ["완료하다", "완전한"],    "regard": ["간주하다", "관심"],    "climate": ["기후"],    "protest": ["항의하다"],    "narrow": ["좁은"],    "target": ["목표", "대상을 정하다"],    "imitate": ["모방하다"],    "whether": ["~인지 아닌지"],    "swallow": ["삼키다", "제비"],    "flame": ["불꽃"],    "concern": ["관심", "걱정"],    "estimate": ["추정하다", "견적"],    "anxious": ["걱정하는", "열망하는"],    "miserable": ["비참한"],    "divide": ["나누다"],    "exceed": ["초과하다"],    "depressed": ["우울한"],    "therapy": ["치료", "요법"],    "adjust": ["조절하다", "적응하다"],    "senior": ["선배", "고령자"],    "joint": ["관절", "공동의"],    "whatever": ["무엇이든"],    "snore": ["코를 골다"],    "breath": ["숨", "호흡"],    "vision": ["시력", "환상"],    "altogether": ["완전히", "모두 합쳐"],    "shut": ["닫다"],    "wander": ["헤매다", "배회하다"],    "random": ["무작위의"],    "shore": ["해안"],    "sincere": ["진실한"],    "salary": ["급여"],    "passive": ["수동적인"],    "system": ["체계", "조직"],    "assume": ["가정하다", "추측하다"],    "delicate": ["섬세한", "민감한"],    "worth": ["가치 있는"],    "though": ["비록 ~일지라도"],    "paste": ["풀", "반죽"],    "calculate": ["계산하다"],    "grateful": ["감사하는"],    "honest": ["정직한"],    "multiple": ["다수의", "배수의"],    "thrill": ["전율"],    "commercial": ["상업적인", "광고"],    "nature": ["자연", "본성"],    "quantity": ["양"],    "microwave": ["전자레인지"],    "worship": ["예배하다", "숭배"],    "negative": ["부정적인"],    "domestic": ["가정의", "국내의"],    "pioneer": ["개척자"],    "defeat": ["패배시키다"],    "explode": ["폭발하다"],    "burst": ["터지다"],    "agent": ["대리인"],    "potential": ["잠재적인"],    "inspect": ["검사하다"],    "disturb": ["방해하다"],    "leak": ["새다"],    "standard": ["표준", "기준"],    "preserve": ["보존하다"],    "index": ["색인", "지표"],    "biography": ["전기"],    "laboratory": ["실험실"],    "acid": ["산", "산성의"],    "peel": ["껍질을 벗기다"],    "statue": ["조각상"],    "tragedy": ["비극"],    "prime": ["주요한", "최고의"],    "pray": ["기도하다"],    "arrange": ["배열하다", "정리하다"],    "contrast": ["대조"],    "defect": ["결점"],    "harmony": ["조화"],    "pale": ["창백한"],    "despite": ["~에도 불구하고"],    "rival": ["경쟁자"],    "faint": ["희미한", "기절하다"],    "fever": ["열"],    "classify": ["분류하다"],    "relieve": ["완화하다", "안도하게 하다"],    "format": ["형식"],    "faith": ["믿음", "신념"],    "holy": ["신성한"],    "sacred": ["신성한"],    "wire": ["철사", "전선"],    "million": ["백만"],    "classic": ["고전적인", "최고 수준의"],    "capture": ["포착하다", "생포하다"],    "miss": ["그리워하다", "놓치다"],    "humor": ["유머"],    "approve": ["승인하다", "찬성하다"],    "lecture": ["강의"],    "bottom": ["바닥"],    "attention": ["주의", "집중"],    "terminal": ["터미널", "말기의"],    "breeze": ["산들바람"],    "assess": ["평가하다"],    "monitor": ["모니터하다", "화면"],    "fountain": ["분수"],    "evaluate": ["평가하다"],    "consult": ["상담하다"],    "counsel": ["조언", "상담"],    "discipline": ["훈육", "규율"],    "suitable": ["적합한"],    "appetite": ["식욕"],    "sum": ["합계", "금액"],    "harbor": ["항구"],    "superb": ["최고의"],    "dismiss": ["해고하다", "묵살하다"],    "retire": ["은퇴하다"],    "beyond": ["~을 넘어서"],    "mercy": ["자비"],    "educate": ["교육하다"],    "tidy": ["깔끔한"],    "aisle": ["복도", "통로"],    "fashion": ["패션", "방식"],    "beat": ["이기다", "두드리다"],    "due": ["~할 예정인", "기한이 된"],    "toast": ["토스트", "건배"],    "insult": ["모욕하다"],    "cell": ["세포", "작은 방"],    "instruction": ["지시", "설명"],    "assign": ["배정하다"],    "semester": ["학기"],    "scramble": ["재빨리 움직이다", "뒤섞다"],    "fiber": ["섬유"],    "phenomenon": ["현상"],    "steel": ["철강"],    "diverse": ["다양한"],    "shallow": ["얕은"],    "positive": ["긍정적인"],    "shift": ["변화", "이동하다"],    "thorough": ["철저한"],    "embarrass": ["당황하게 하다"],    "amuse": ["즐겁게 하다"],    "raw": ["날것의"],    "astonish": ["놀라게 하다"],    "interact": ["상호작용하다"],    "gap": ["차이", "틈"],    "entry": ["입장", "참가"],    "boast": ["자랑하다"],    "select": ["선택하다"],    "plenty": ["풍부함"],    "display": ["전시하다", "보여주다"],    "broad": ["넓은"],    "ambitious": ["야심 있는"],    "confident": ["자신감 있는"],    "modest": ["겸손한"],    "privacy": ["사생활"],    "logic": ["논리"],    "crush": ["으깨다", "홀딱 반함"],    "tender": ["부드러운"],    "illustrate": ["설명하다", "삽화를 넣다"],    "confirm": ["확인하다"],    "accompany": ["동행하다"],    "baggage": ["수하물"],    "departure": ["출발"],    "destination": ["목적지"],    "chief": ["주요한", "장"],    "column": ["기둥", "칼럼"],    "aggressive": ["공격적인"],    "greedy": ["탐욕스러운"],    "bay": ["만"],    "oxygen": ["산소"],    "submarine": ["잠수함"],    "accurate": ["정확한"],    "effective": ["효과적인"],    "dynamic": ["역동적인"],    "muscle": ["근육"],    "cancer": ["암"],    "trace": ["추적하다", "흔적"],    "justify": ["정당화하다"],    "pace": ["속도"],    "compete": ["경쟁하다"],    "scratch": ["긁다"],    "athlete": ["운동선수"],    "register": ["등록하다"],    "rotten": ["썩은"],    "security": ["보안", "안전"],    "paralyze": ["마비시키다"],    "wound": ["상처", "부상을 입히다"],    "generation": ["세대"],    "circumstance": ["상황"],    "infect": ["감염시키다"],    "rescue": ["구조하다"],    "expand": ["확장하다"],    "disaster": ["재난"],    "access": ["접근"],    "efficient": ["효율적인"],    "temporary": ["일시적인"],    "reduce": ["줄이다"],    "strategy": ["전략"],    "pause": ["멈춤"],    "caution": ["주의", "경고"],    "establish": ["설립하다", "확립하다"],    "recover": ["회복하다"],    "identity": ["정체성"],    "rural": ["시골의"],    "urban": ["도시의"],    "cooperate": ["협력하다"],    "contribute": ["기여하다"],    "approach": ["접근하다"],    "maintain": ["유지하다"],    "severe": ["심각한"],    "absorb": ["흡수하다"],    "define": ["정의하다"],    "penalty": ["처벌", "벌금"],    "property": ["재산", "특성"],    "credit": ["신용", "공로"],    "fund": ["자금"],    "faucet": ["수도꼭지"],    "forecast": ["예보"],    "loan": ["대출"],    "abandon": ["버리다", "포기하다"],    "stock": ["주식", "재고"],    "relate": ["관련시키다"],    "import": ["수입하다"],    "export": ["수출하다"],    "commerce": ["상업"],    "profit": ["이익"],    "stable": ["안정된"],    "poverty": ["가난"],    "finance": ["금융", "재무"],    "asset": ["자산"],    "desperate": ["절망적인", "필사적인"],    "congress": ["의회"],    "council": ["의회", "회의"],    "decay": ["부패", "쇠퇴"],    "motion": ["운동", "동작"],    "committee": ["위원회"],    "candidate": ["후보자"],    "democracy": ["민주주의"],    "reform": ["개혁하다"],    "leap": ["도약"],    "appeal": ["호소하다", "매력"],    "venture": ["모험"],    "advantage": ["장점"],    "demonstrate": ["증명하다", "시연하다"],    "criticize": ["비판하다"],    "release": ["석방하다", "출시하다"],    "conflict": ["갈등", "충돌"],    "engage": ["관여하다", "약혼하다"],    "ultimate": ["궁극적인"],    "distribute": ["분배하다"],    "principle": ["원칙"],    "racial": ["인종의"],    "province": ["지방", "도"],    "although": ["비록 ~일지라도"],    "legal": ["법률의", "합법적인"],    "deceive": ["속이다"],    "inspire": ["영감을 주다"],    "definite": ["명확한"],    "unite": ["결합하다"],    "civil": ["시민의"],    "promote": ["홍보하다", "승진시키다"],    "murder": ["살인"],    "copyright": ["저작권"],    "forbid": ["금지하다"],    "conscience": ["양심"],    "pretend": ["~인 척하다"],    "troop": ["군대"],    "territory": ["영토"],    "reveal": ["드러내다"],    "faithful": ["충실한"],    "interpret": ["해석하다", "통역하다"],    "declare": ["선언하다"],    "manufacture": ["제조하다"],    "product": ["제품"],    "output": ["출력", "생산량"],    "theory": ["이론"],    "district": ["구역", "지역"],    "outstanding": ["뛰어난"],    "genuine": ["진짜의", "순수한"],    "extend": ["연장하다", "확장하다"],    "complement": ["보완하다"],    "revolution": ["혁명"],    "automatic": ["자동의"],    "mineral": ["광물"],    "gene": ["유전자"],    "cultivate": ["경작하다", "기르다"],    "remark": ["말하다", "주목하다"],    "nuclear": ["핵의"],    "conquer": ["정복하다"],    "assemble": ["조립하다", "모으다"],    "heritage": ["유산"],    "species": ["종"],    "exhaust": ["고갈시키다", "배기가스"],    "shortage": ["부족"],    "restrict": ["제한하다"],    "fossil": ["화석"],    "volcano": ["화산"],    "summit": ["정상"],    "facility": ["시설"],    "occupy": ["점령하다", "차지하다"],    "lightning": ["번개"],    "horizon": ["지평선"],    "marine": ["해양의"],    "cliff": ["절벽"],    "artificial": ["인공의"],    "emerge": ["나타나다"],    "dispose": ["배치하다", "처분하다"],    "conserve": ["보존하다"],    "atmosphere": ["대기", "분위기"],    "melt": ["녹다"],    "layer": ["층"],    "confess": ["자백하다"],    "suspect": ["의심하다"],    "commit": ["저지르다", "위탁하다"],    "guilty": ["유죄의"],    "trial": ["재판", "시험"],    "threat": ["위협"],    "violent": ["폭력적인"],    "accuse": ["비난하다", "고소하다"],    "agriculture": ["농업"],    "harvest": ["수확"],    "pollute": ["오염시키다"],    "philosophy": ["철학"],    "combine": ["결합하다"],    "extreme": ["극도로"],    "resolve": ["해결하다", "결심하다"],    "control": ["조절하다", "통제하다"],    "noble": ["고귀한"],    "colleague": ["동료"],    "swear": ["맹세하다", "욕하다"],    "adapt": ["적응하다"],    "architect": ["건축가"],    "structure": ["구조"],    "garage": ["차고"],    "overseas": ["해외의"],    "colony": ["식민지"],    "urgent": ["긴급한"],    "pronunciation": ["발음"],    "license": ["면허"],    "resist": ["저항하다"],    "vehicle": ["차량"],    "operate": ["수술하다", "작동하다"],    "tense": ["긴장된"],    "significant": ["중요한"],    "motivate": ["동기를 부여하다"],    "contract": ["계약", "수축하다"],    "frighten": ["겁주다"],    "routine": ["일상"],    "impact": ["영향", "충격"],    "instance": ["예", "사례"],    "concrete": ["구체적인", "콘크리트"],    "insert": ["삽입하다"],    "beneath": ["~의 아래에"],    "visual": ["시각적인"],    "grant": ["승인하다", "보조금"],    "bundle": ["다발"],    "adopt": ["입양하다", "채택하다"],    "string": ["끈", "줄"],    "leftover": ["남은 음식"],    "lack": ["부족"],    "attitude": ["태도"],    "code": ["암호", "규범"],    "gradually": ["점차"],    "overall": ["전반적인"],    "construct": ["건설하다"],    "deny": ["부인하다"],    "specific": ["특정한"],    "grab": ["붙잡다"],    "mirror": ["거울"],    "frequent": ["빈번한"],    "logical": ["논리적인"],    "battle": ["전투"],    "scatter": ["흩뿌리다"],    "visible": ["눈에 보이는"],    "barrier": ["장벽"],    "ingredient": ["재료", "성분"],    "till": ["~까지"],    "practical": ["실용적인"],    "junk": ["쓰레기"],    "insight": ["통찰력"],    "beverage": ["음료"],    "cottage": ["오두막"],    "spill": ["엎지르다"],    "chill": ["냉기"],    "sigh": ["한숨 쉬다"],    "portable": ["휴대용의"],    "apart": ["떨어져서"],    "persuade": ["설득하다"],    "postpone": ["연기하다"],    "squeeze": ["짜다"],    "insist": ["주장하다"],    "aboard": ["탑승한"],    "transfer": ["이동하다", "환승하다"],    "transport": ["운송하다"],    "virtual": ["가상의"],    "motive": ["동기"],    "alter": ["변경하다"],    "intellectual": ["지적인"],    "growth": ["성장"],    "route": ["경로"],    "immediate": ["즉각적인"],    "popularity": ["인기"],    "slight": ["약간의"],    "private": ["개인적인"],    "wheat": ["밀"],    "landscape": ["풍경"],    "feature": ["특징", "이목구비"],    "internal": ["내부의"],    "loss": ["손실"],    "appropriate": ["적절한"],    "restore": ["회복하다"],    "struggle": ["투쟁하다", "애쓰다"],    "critic": ["비평가"],    "moral": ["도덕적인"],    "capable": ["능력 있는"],    "junior": ["후배"],    "absent": ["결석한"],    "ambassador": ["대사"],    "ideal": ["이상적인"],    "encounter": ["맞닥뜨리다"],    "ceremony": ["의식"],    "occasion": ["때", "경우"],    "tone": ["어조"],    "frankly": ["솔직히"],    "mount": ["산", "오르다"],    "burden": ["부담"],    "enormous": ["거대한"],    "external": ["외부의"],    "lifetime": ["평생"],    "arrive": ["도착하다"],    "terrific": ["멋진"],    "bump": ["부딪히다"],    "glory": ["영광"],    "instrument": ["도구", "악기"],    "associate": ["관련시키다"],    "rate": ["비율", "평가하다"],    "personality": ["성격"],    "brief": ["간결한"],    "reward": ["보상"],    "creature": ["생명체"],    "policy": ["정책"],    "aspect": ["측면"],    "scold": ["꾸짖다"],    "proper": ["적절한"],    "typical": ["전형적인"],    "entrance": ["입구"],    "possess": ["소유하다"],    "inn": ["여관"],    "acquire": ["습득하다"],    "unlike": ["~와 달리"],    "envelope": ["봉투"],    "celebrate": ["축하하다"],    "digest": ["소화하다"],    "devote": ["바치다", "헌신하다"],    "voyage": ["항해"],    "negotiate": ["협상하다"],    "complicated": ["복잡한"],    "reservation": ["예약"],    "surround": ["둘러싸다"],    "millionaire": ["백만장자"],    "stain": ["얼룩"],    "indicate": ["나타내다"],    "regulate": ["규제하다"],    "sprinkle": ["뿌리다"],    "twist": ["비틀다"],    "applaud": ["박수갈채를 보내다"],    "graze": ["풀을 뜯다"],    "core": ["핵심"],    "comfort": ["안락"],    "assist": ["돕다"],    "empire": ["제국"],    "beam": ["빛줄기"],    "steep": ["가파른"],    "crack": ["갈라진 틈"],    "incident": ["사건"],    "content": ["내용", "만족하는"],    "career": ["경력"],    "function": ["기능"],    "port": ["항구"],    "tropical": ["열대의"],    "clown": ["광대"],    "informal": ["비공식적인"],    "annual": ["연례의"],    "complex": ["복잡한"],    "temperature": ["온도"],    "proof": ["증거"],    "client": ["고객"],    "frustrate": ["좌절시키다"],    "within": ["~ 이내에"],    "grocery": ["식료품"],    "ceiling": ["천장"],    "disappear": ["사라지다"],    "cope": ["대처하다"],    "fate": ["운명"],    "accomplish": ["성취하다"],    "convince": ["확신시키다"],    "quarrel": ["말다툼"],    "stir": ["휘젓다"],    "attain": ["달성하다"],    "funeral": ["장례식"],    "attract": ["끌다"],    "recipe": ["조리법"],    "companion": ["동료"],    "please": ["즐겁게 하다", "제발"],    "glue": ["풀"],    "haste": ["서두름"],    "germ": ["세균"],    "indeed": ["정말로"],    "quarter": ["4분의 1"],    "plain": ["명백한", "평원"],    "gradual": ["점진적인"],    "permanent": ["영구적인"],    "sort": ["종류", "분류하다"],    "anchor": ["닻"],    "jealous": ["질투하는"],    "confidence": ["신뢰", "자신감"],    "factory": ["공장"],    "mature": ["성숙한"],    "propose": ["제안하다"],    "pursue": ["추구하다"],    "calm": ["침착한"],    "distinguish": ["구별하다"],    "encourage": ["격려하다"],    "responsible": ["책임 있는"],    "announce": ["발표하다"],    "rely": ["의지하다"],    "firm": ["단단한", "회사"],    "sheet": ["종이 한 장"],    "brilliant": ["훌륭한"],    "chapter": ["장"],    "exclude": ["배제하다"],    "survey": ["조사"],    "concentrate": ["집중하다"],    "debt": ["빚"],    "gently": ["부드럽게"],    "engineer": ["기술자"],    "button": ["단추"],    "wizard": ["마법사"],    "announcer": ["아나운서"],    "adventure": ["모험"],    "carefully": ["조심스럽게"],    "sensitive": ["민감한"],    "translation": ["번역"],    "campaign": ["캠페인"],    "globe": ["지구"],    "traditional": ["전통적인"],    "oppose": ["반대하다"],    "discussion": ["토론"],    "pollution": ["오염"],    "secure": ["안전한"],    "inquiry": ["조사", "문의"],    "signature": ["서명"],    "etiquette": ["예의"],    "exclusive": ["배제적인", "독점적인"],    "prohibit": ["금지하다"],    "catalogue": ["목록"],    "stress": ["스트레스", "강조하다"],    "champion": ["우승자"],    "disappoint": ["실망시키다"],    "jewelry": ["보석류"],    "absolutely": ["절대적으로"],    "seaweed": ["해초"],    "grace": ["우아함"],    "extracurricular": ["방과 후의"],    "intense": ["강렬한"],    "probability": ["확률"],    "kneel": ["무릎 꿇다"],    "missionary": ["선교사"],    "creep": ["기다"],    "oppression": ["억압"],    "dove": ["비둘기"],    "manager": ["경영자"],    "undergo": ["겪다"],    "despair": ["절망"],    "erase": ["지우다"],    "massive": ["거대한"],    "respectful": ["공경하는"],    "extraordinary": ["비범한"],    "pave": ["포장하다"],    "depth": ["깊이"],    "ethnic": ["민족의"],    "marriage": ["결혼"],    "treatment": ["대우", "치료"],    "resident": ["거주자"],    "thrilling": ["전율을 느끼게 하는"],    "concerned": ["걱정하는", "관심 있는"],    "instruct": ["지시하다"],    "loosen": ["풀다"],    "tension": ["긴장"],    "throughout": ["도처에", "내내"],    "consequence": ["결과"],    "absence": ["부재", "결석"],    "foresee": ["예견하다"],    "excitement": ["흥분"],    "container": ["그릇", "용기"],    "imply": ["암시하다"],    "portion": ["부분"],    "punctual": ["시간을 엄수하는"],    "detect": ["탐지하다"],    "technical": ["기술적인"],    "anxiety": ["불안"],    "threaten": ["위협하다"],    "barely": ["간신히"],    "omit": ["생략하다"],    "addicted": ["중독된"],    "antique": ["골동품"],    "secondhand": ["중고의"],    "competitive": ["경쟁적인"],    "robber": ["도둑"],    "exhausted": ["기진맥진한"],    "architecture": ["건축"],    "royalty": ["왕족"],    "lighten": ["밝게 하다"],    "homeless": ["노숙자"],    "go through": ["겪다"],    "crowd": ["군중"],    "seminar": ["세미나"],    "lung": ["폐"],    "relative": ["친척", "상대적인"],    "harmful": ["해로운"],    "excite": ["흥분시키다"],    "reality": ["현실"],    "pitcher": ["투수"],    "classical": ["고전적인"],    "energetic": ["정력적인"],    "cotton": ["면화"],    "activity": ["활동"],    "focus": ["집중하다"],    "definitely": ["절대적으로"],    "academy": ["학술원"],    "space": ["공간", "우주"],    "politic": ["정치적인"],    "independence": ["독립"],    "immediately": ["즉시"],    "reasonable": ["합리적인"],    "meadow": ["목초지"],    "snack": ["간식"],    "fiction": ["소설"],    "transportation": ["수송"],    "underneath": ["~의 아래에"],    "fantastic": ["환상적인"],    "technique": ["기술"],    "starve": ["굶주리다"],    "prior": ["사전의"],    "cradle": ["요람"],    "iceberg": ["빙산"],    "business": ["사업"],    "adult": ["성인"],    "mere": ["단순한"],    "personal": ["개인적인"],    "addition": ["추가"],    "appearance": ["외모", "등장"],    "against": ["~에 반대하여"],    "pacific": ["평화로운", "태평양"],    "resume": ["재개하다", "이력서"],    "permission": ["허가"],    "organization": ["조직"],    "academic": ["학업의"],    "marble": ["대리석", "구슬"],    "injury": ["부상"],    "idiom": ["관용구"],    "unfortunately": ["불행하게도"],    "parade": ["행진"],    "humanity": ["인류"],    "optimistic": ["낙관적인"],    "garlic": ["마늘"],    "selfish": ["이기적인"],    "moisture": ["습기"],    "wagon": ["마차"],    "glitter": ["반짝이다"],    "interview": ["면접"],    "fright": ["공포"],    "seatbelt": ["안전벨트"],    "microscope": ["현미경"],    "patent": ["특허"],    "distinct": ["뚜렷한"],    "exit": ["출구"],    "convert": ["전환하다"],    "oyster": ["굴"],    "illusion": ["환상"],    "scary": ["무서운"],    "expedition": ["탐험"],    "sauce": ["소스"],    "magic": ["마법"],    "pressure": ["압력"],    "curious": ["궁금한"],    "subtle": ["미묘한"],    "apologize": ["사과하다"],    "solution": ["해결책"],    "luckily": ["운 좋게도"],    "wreck": ["난파선", "파괴하다"],    "shark": ["상어"],    "hold on to": ["~을 꼭 잡다"],    "go over": ["검토하다"],    "throne": ["왕좌"],    "sting": ["찌르다"],    "genetic": ["유전적인"],    "relief": ["안도", "구호"],    "temper": ["성질"],    "loop": ["고리"],    "appliance": ["가전제품"],    "trait": ["특성"],    "moderate": ["적당한"],    "plural": ["복수의"],    "imagination": ["상상력"],    "sparkle": ["반짝이다"],    "vowel": ["모음"],    "ethic": ["윤리"],    "tame": ["길들이다"],    "argument": ["논쟁"],    "enroll": ["등록하다"],    "rid": ["제거하다"],    "vertical": ["수직의"],    "communication": ["의사소통"],    "comet": ["혜성"],    "conclusion": ["결론"],    "impressive": ["인상적인"],    "resign": ["사퇴하다"],    "interior": ["실내"],    "spacecraft": ["우주선"],    "recite": ["낭독하다"],    "development": ["개발"],    "intelligence": ["지능"],    "economic": ["경제의"],    "revenge": ["복수"],    "literal": ["문자 그대로의"],    "valid": ["유효한"],    "assignment": ["과제"],    "tempt": ["유혹하다"],    "modify": ["수정하다"],    "miner": ["광부"],    "breast": ["가슴"],    "federal": ["연방의"],    "basement": ["지하"],    "fertilizer": ["비료"],    "splendid": ["훌륭한"],    "copper": ["구리"],    "infection": ["감염"],    "twisted": ["꼬인"],    "professional": ["전문적인"],    "wavy": ["물결 모양의"],    "dedication": ["헌신"],    "patience": ["인내"],    "counselor": ["상담사"],    "escalate": ["확대되다"],    "explanation": ["설명"],    "parliament": ["의회"],    "factual": ["사실에 기반한"],    "channel": ["경로", "채널"],    "span": ["기간"],    "unbelievable": ["믿을 수 없는"],    "nutrient": ["영양소"],    "freezer": ["냉동고"],    "arrogant": ["오만한"],    "inference": ["추론"],    "landmark": ["이정표"],    "mechanical": ["기계적인"],    "geography": ["지리"],    "contestant": ["참가자"],    "ape": ["유인원"],    "ecosystem": ["생태계"],    "superstition": ["미신"],    "operator": ["작업자"],    "wildlife": ["야생동물"],    "cemetery": ["공동묘지"],    "conference": ["회의"],    "shed": ["창고", "흘리다"],    "unexpected": ["예기치 못한"],    "satisfied": ["만족하는"],    "ray": ["광선"],    "adolescence": ["청소년기"],    "underwater": ["수중의"],    "construction": ["건설"],    "discourage": ["낙담시키다"],    "get along with": ["~와 잘 지내다"],    "pay off": ["성과를 거두다"],    "sign up for": ["~에 등록하다"],    "show off": ["자랑하다"],    "run out": ["다 떨어지다"],    "keep in touch": ["연락하고 지내다"],    "regardless of": ["~에 상관없이"],    "put off": ["연기하다"],    "play a role in": ["~에서 역할을 하다"],    "pay attention to": ["~에 주의를 기울이다"],    "stand out": ["두드러지다"],    "on purpose": ["고의로"],    "make up for": ["~을 보충하다"],    "make sure": ["확인하다"],    "look up": ["찾아보다"],    "put up with": ["참다"],    "break down": ["고장 나다"],    "belong to": ["~에 속하다"],    "stand for": ["상징하다"],    "stay away from": ["~로부터 떨어져 있다"],    "meanwhile": ["그동안에"],    "come to mind": ["생각나다"],    "from now on": ["이제부터"],    "focus on": ["~에 집중하다"],    "figure out": ["이해하다"],    "in need": ["어려움에 처한"],    "cut off": ["자르다", "차단하다"],    "cut down on": ["~을 줄이다"],    "come up with": ["생각해내다"],    "come across": ["우연히 마주치다"],    "stick to": ["고수하다"],    "carry out": ["수행하다"],    "bring about": ["야기하다"],    "deal with": ["다루다"],    "break out": ["발생하다"],    "in the middle of": ["~의 도중에"],    "lead to": ["~로 이어지다"],    "turn a into b": ["A를 B로 바꾸다"],    "slope": ["경사"],    "essence": ["본질"],    "peninsula": ["반도"],    "impressed": ["감명받은"],    "neighborhood": ["이웃"],    "orbit": ["궤도"],    "punctuation": ["구두점"],    "optical": ["시각적인"],    "prejudice": ["편견"],    "defense": ["방어"],    "nutrition": ["영양"],    "complaint": ["불평"],    "political": ["정치적인"],    "habitat": ["서식지"],    "substitute": ["대체하다"],    "immigrate": ["이민 오다"],    "impossible": ["불가능한"],    "attraction": ["매력"],    "evaporate": ["증발하다"],    "drip": ["방울"],    "variety": ["다양성"], 
  "ability": ["능력"],
  "allow": ["허락하다"],
  "amaze": ["놀라게 하다"],
  "ancient": ["고대의"],
  "angle": ["각도", "관점"],
  "audience": ["청중", "관객"],
  "award": ["상", "수여하다"],
  "awful": ["끔찍한"],
  "background": ["배경", "배경지식"],
  "basis": ["기초", "기준"],
  "beg": ["간청하다"],
  "bet": ["내기하다", "확신하다"],
  "bury": ["묻다"],
  "cause": ["원인", "야기하다"],
  "certain": ["확실한"],
  "challenge": ["도전", "도전하다"],
  "cheat": ["속이다", "부정행위를 하다"],
  "cheerful": ["쾌활한"],
  "communicate": ["의사소통하다"],
  "congratulate": ["축하하다"],
  "connect": ["연결하다"],
  "consider": ["고려하다"],
  "contact": ["연락하다", "접촉"],
  "court": ["법정", "궁정"],
  "curiosity": ["호기심"],
  "customer": ["손님", "고객"],
  "damage": ["손상", "손상을 주다"],
  "deadline": ["마감일"],
  "drag": ["끌다"],
  "duty": ["의무", "직무"],
  "embarrassed": ["당황한"],
  "environment": ["환경"],
  "eventually": ["결국"],
  "exactly": ["정확히"],
  "failure": ["실패"],
  "female": ["여성의", "여성"],
  "flavor": ["맛", "풍미"],
  "flow": ["흐르다", "흐름"],
  "fold": ["접다"],
  "forgive": ["용서하다"],
  "form": ["형태", "형성하다"],
  "fortune": ["행운", "재산"],
  "fuel": ["연료"],
  "furthermore": ["게다가"],
  "gain": ["얻다", "증가"],
  "genius": ["천재"],
  "global": ["전 세계의"],
  "heal": ["치유하다"],
  "hire": ["고용하다"],
  "injure": ["다치게 하다"],
  "lately": ["최근에"],
  "legend": ["전설"],
  "lift": ["들어 올리다"],
  "literature": ["문학"],
  "local": ["지역의"],
  "lonely": ["외로운"],
  "mate": ["친구", "짝"],
  "movement": ["움직임", "운동"],
  "mysterious": ["신비한"],
  "native": ["토착의", "원주민"],
  "nod": ["끄덕이다"],
  "offer": ["제안하다", "제안"],
  "official": ["공식의", "공무원"],
  "opinion": ["의견"],
  "ordinary": ["평범한"],
  "pile": ["더미", "쌓다"],
  "planet": ["행성"],
  "plant": ["식물", "공장"],
  "poetry": ["시"],
  "possibility": ["가능성"],
  "pour": ["붓다"],
  "praise": ["칭찬하다", "칭찬"],
  "precious": ["소중한"],
  "previous": ["이전의"],
  "process": ["과정", "처리하다"],
  "quest": ["탐구", "추구"],
  "rank": ["등급", "등급을 매기다"],
  "recently": ["최근에"],
  "recommend": ["추천하다"],
  "record": ["기록", "기록하다"],
  "relationship": ["관계"],
  "relax": ["긴장을 풀다"],
  "request": ["요청", "요청하다"],
  "return": ["돌아오다", "돌려주다"],
  "review": ["복습", "검토하다"],
  "risk": ["위험", "위험을 무릅쓰다"],
  "root": ["뿌리", "근원"],
  "rough": ["거친", "대략의"],
  "scare": ["겁주다", "공포"],
  "scream": ["비명을 지르다", "비명"],
  "shade": ["그늘", "색조"],
  "shelf": ["선반"],
  "similar": ["비슷한"],
  "sink": ["가라앉다"],
  "situation": ["상황"],
  "spin": ["돌다", "돌리다"],
  "survival": ["생존"],
  "switch": ["바꾸다", "스위치"],
  "systematic": ["체계적인"],
  "task": ["과제"],
  "thick": ["두꺼운"],
  "tradition": ["전통"],
  "trend": ["경향", "유행"],
  "unique": ["독특한"],
  "warn": ["경고하다"],
  "weigh": ["무게를 재다"],
  "whisper": ["속삭이다"],
  "participate": ["참여하다"],
  "locate": ["위치를 찾다", "위치하다"],
  "accept": ["받아들이다"],
  "ignore": ["무시하다"],
  "essential": ["필수적인"],
  "limit": ["한계", "제한하다"],
  "behave": ["행동하다"],
  "argue": ["주장하다", "다투다"],
  "occur": ["발생하다"],
  "explore": ["탐험하다", "탐구하다"],
  "active": ["활동적인"],
  "likewise": ["마찬가지로"],
  "admit": ["인정하다", "입장을 허락하다"],
  "evidence": ["증거"],
  "differ": ["다르다"],
  "conclude": ["결론짓다"],
  "determine": ["결정하다"],
  "available": ["이용 가능한"],
  "describe": ["묘사하다"],
  "public": ["공공의", "대중"],
  "separate": ["분리하다", "별개의"],
  "expectation": ["기대"],
  "innocent": ["무죄의", "순진한"],
  "national": ["국가의"],
  "depend": ["의존하다"],
  "duration": ["지속 기간"],
  "general": ["일반적인", "장군"],
  "introduce": ["소개하다"],
  "latter": ["후자의"],
  "advise": ["조언하다"],
  "decorate": ["장식하다"],
  "enable": ["가능하게 하다"],
  "decade": ["10년"],
  "aware": ["알고 있는"],
  "react": ["반응하다"],
  "tend": ["경향이 있다"],
  "intend": ["의도하다"],
  "equipment": ["장비"],
  "respond": ["응답하다"],
  "realistic": ["현실적인"],
  "steady": ["꾸준한", "안정된"],
  "vary": ["다르다", "변하다"],
  "alarm": ["경보", "놀라게 하다"],
  "constant": ["지속적인", "일정한"],
  "deserve": ["~할 가치가 있다"],
  "generate": ["발생시키다"],
  "package": ["포장하다", "소포"],
  "analyze": ["분석하다"],
  "identify": ["확인하다", "식별하다"],
  "emphasize": ["강조하다"],
  "detail": ["세부 사항"],
  "clue": ["단서"],
  "absolute": ["절대적인"],
  "option": ["선택권"],
  "guard": ["지키다", "경비원"],
  "emergency": ["비상사태"],
  "addict": ["중독자", "중독시키다"],
  "owe": ["빚지고 있다"],
  "recall": ["기억해 내다", "회수하다"],
  "condition": ["상태", "조건"],
  "delay": ["지연", "지연시키다"],
  "compose": ["구성하다", "작곡하다"],
  "cancel": ["취소하다"],
  "slip": ["미끄러지다"],
  "triumph": ["승리"],
  "region": ["지역"],
  "pose": ["자세를 취하다", "제기하다"],
  "surface": ["표면", "표면화되다"],
  "predict": ["예측하다"],
  "pure": ["순수한"],
  "seek": ["찾다", "추구하다"],
  "instant": ["즉각적인", "순간"],
  "dramatic": ["극적인"],
  "guarantee": ["보장하다", "보증"],
  "fulfill": ["이행하다", "달성하다"],
  "substance": ["물질", "본질"],
  "identical": ["동일한"],
  "independent": ["독립적인"],
  "casual": ["격식을 차리지 않은"],
  "status": ["지위", "상태"],
  "expose": ["드러내다", "노출시키다"],
  "concept": ["개념"],
  "summarize": ["요약하다"],
  "memorize": ["암기하다"],
  "precise": ["정확한"],
  "trap": ["덫", "가두다"],
  "trick": ["속임수", "속이다"],
  "isolate": ["고립시키다"],
  "spare": ["남는", "아끼다"],
  "reproduce": ["재생산하다", "복제하다"],
  "apparent": ["분명한"],
  "reject": ["거절하다"],
  "component": ["구성 요소"],
  "breakdown": ["고장", "붕괴"],
  "universal": ["보편적인"],
  "awaken": ["깨우다"],
  "await": ["기다리다"],
  "transform": ["변형시키다"],
  "majority": ["대다수"],
  "minority": ["소수"],
  "additional": ["추가의"],
  "worthwhile": ["가치 있는"],
  "stretch": ["늘이다", "뻗다"],
  "fame": ["명성"],
  "handle": ["다루다", "처리하다"],
  "refresh": ["상쾌하게 하다"],
  "contrary": ["반대의"],
  "disagree": ["동의하지 않다"],
  "defend": ["방어하다"],
  "devise": ["고안하다"],
  "revise": ["수정하다"],
  "framework": ["틀", "뼈대"],
  "qualify": ["자격을 주다", "자격을 얻다"],
  "assure": ["확신시키다", "보장하다"],
  "storage": ["저장", "보관"],
  "nevertheless": ["그럼에도 불구하고"],
  "dust": ["먼지"],
  "debate": ["논쟁", "토론하다"],
  "likely": ["가능성 있는", "아마"],
  "lessen": ["줄이다"],
  "objective": ["객관적인", "목표"],
  "subjective": ["주관적인"],
  "simplicity": ["단순함"],
  "track": ["추적하다", "길"],
  "sufficient": ["충분한"],
  "obligation": ["의무"],
  "spoil": ["망치다", "버릇없이 키우다"],
  "gaze": ["응시하다", "응시"],
  "glance": ["흘끗 보다", "흘끗 봄"],
  "document": ["문서"],
  "interfere": ["방해하다"],
  "strive": ["노력하다"],
  "unify": ["통합하다"],
  "fancy": ["화려한", "좋아하다"],
  "union": ["연합", "조합"],
  "mobile": ["이동하는", "휴대전화"],
  "feedback": ["피드백", "반응"],
  "bounce": ["튀다"],
  "vital": ["매우 중요한"],
  "examine": ["조사하다", "검사하다"],
  "resource": ["자원"],
  "abstract": ["추상적인", "개요"],
  "permit": ["허락하다", "허가증"],
  "acknowledge": ["인정하다"],
  "satisfy": ["만족시키다", "충족시키다"],
  "fasten": ["매다", "고정하다"],
  "medium": ["매체", "중간의"],
  "activate": ["활성화하다"],
  "greet": ["인사하다", "맞이하다"],
  "intimate": ["친밀한"],
  "opponent": ["상대", "반대자"],
  "victim": ["희생자", "피해자"],
  "versus": ["~대", "대(對)"],
  "via": ["~을 거쳐"],
  "ease": ["완화하다", "편안함"],
  "dash": ["돌진하다"],
  "soak": ["적시다", "담그다"],
  "chamber": ["방", "실"],
  "expel": ["쫓아내다"],
  "session": ["회기", "시간"],
  "ensure": ["반드시 ~하게 하다"],
  "insure": ["보험에 들다"],
  "warrant": ["정당화하다", "보증하다"],
  "outline": ["개요", "윤곽을 그리다"],
  "withdraw": ["물러나다", "인출하다"],
  "overlook": ["간과하다", "내려다보다"],
  "vacant": ["비어 있는"],
  "habitual": ["습관적인"],
  "abnormal": ["비정상적인"],
  "deliberate": ["고의의", "신중한"],
  "periodic": ["주기적인"],
  "disorder": ["혼란", "장애"],
  "slam": ["쾅 닫다"],
  "fascinate": ["매료시키다"],
  "fragile": ["깨지기 쉬운"],
  "durable": ["내구성이 있는"],
  "obstacle": ["장애물"],
  "harsh": ["가혹한"],
  "interrupt": ["방해하다", "중단시키다"],
  "persist": ["지속하다", "고집하다"],
  "adequate": ["충분한", "적절한"],
  "resemble": ["닮다"],
  "spark": ["불꽃", "촉발하다"],
  "upcoming": ["다가오는"],
  "gigantic": ["거대한"],
  "collaborate": ["협력하다"],
  "integrate": ["통합하다"],
  "reputation": ["평판"],
  "initial": ["초기의", "머리글자"],
  "launch": ["시작하다", "출시하다"],
  "fruitful": ["결실 있는"],
  "necessity": ["필요", "필수품"],
  "fundamental": ["기본적인"],
  "glare": ["노려보다", "빛나다"],
  "leisurely": ["느긋한"],
  "consistent": ["일관된"],
  "stack": ["쌓다", "더미"],
  "allocate": ["할당하다"],
  "rapid": ["빠른"],
  "eliminate": ["제거하다"],
  "grip": ["꽉 잡다", "쥐는 힘"],
  "dim": ["어두운", "희미한"],
  "diminish": ["줄다", "줄이다"],
  "shrink": ["줄어들다"],
  "rotate": ["회전하다"],
  "accumulate": ["축적하다"],
  "remarkable": ["주목할 만한"],
  "urge": ["촉구하다", "충동"],
  "desirable": ["바람직한"],
  "transmit": ["전달하다", "전염시키다"],
  "anticipate": ["예상하다"],
  "underlying": ["기초가 되는"],
  "sacrifice": ["희생", "희생하다"],
  "namely": ["즉"],
  "abrupt": ["갑작스러운"],
  "strengthen": ["강화하다"],
  "charm": ["매력", "매혹하다"],
  "characteristic": ["특징", "특유의"],
  "proceed": ["진행하다"],
  "innovation": ["혁신"],
  "profound": ["심오한"],
  "reverse": ["뒤집다", "반대"],
  "hence": ["그러므로"],
  "prospect": ["전망"],
  "cherish": ["소중히 여기다"],
  "compact": ["조밀한", "소형의"],
  "utilize": ["이용하다"],
  "flash": ["번쩍이다", "섬광"],
  "unlock": ["열다", "밝히다"],
  "anniversary": ["기념일"],
  "primary": ["주된", "1차의"],
  "weird": ["이상한"],
  "ban": ["금지하다", "금지"],
  "scan": ["훑어보다", "스캔하다"],
  "split": ["나누다", "갈라지다"],
  "rare": ["드문"],
  "compromise": ["타협", "타협하다"],
  "dedicate": ["바치다"],
  "sideeffect": ["부작용"],
  "entire": ["전체의"],
  "conceal": ["숨기다"],
  "fade": ["희미해지다", "사라지다"],
  "stare": ["빤히 보다"],
  "mess": ["엉망", "엉망으로 만들다"],
  "obvious": ["분명한"],
  "embrace": ["껴안다", "받아들이다"],
  "facilitate": ["촉진하다", "용이하게 하다"],
  "transparent": ["투명한", "명백한"],
  "discard": ["버리다"],
  "favorable": ["호의적인", "유리한"],
  "supplement": ["보충하다", "보충물"],
  "implement": ["실행하다", "도구"],
  "scarce": ["부족한"],
  "excess": ["초과", "과다"],
  "abundant": ["풍부한"],
  "administer": ["관리하다", "집행하다"],
  "appoint": ["임명하다"],
  "designate": ["지정하다"],
  "hardship": ["고난"],
  "neutral": ["중립의"],
  "superior": ["우수한", "상사"],
  "inferior": ["열등한", "하위의"],
  "swing": ["흔들리다", "흔들다"],
  "vow": ["맹세하다", "맹세"],
  "accustomed": ["익숙한"],
  "absurd": ["터무니없는"],
  "distract": ["주의를 흩뜨리다"],
  "ongoing": ["진행 중인"],
  "revolve": ["회전하다"],
  "liberate": ["해방하다"],
  "symbolic": ["상징적인"],
  "shield": ["보호하다", "방패"],
  "affair": ["일", "사건"],
  "optimal": ["최적의"],
  "enhance": ["향상시키다"],
  "comprehend": ["이해하다"],
  "overlap": ["겹치다"],
  "excel": ["탁월하다"],
  "repeatedly": ["반복해서"],
  "certificate": ["증명서"],
  "inquire": ["묻다", "문의하다"],
  "fragment": ["조각", "단편"],
  "vague": ["모호한"],
  "extract": ["추출하다", "발췌하다"],
  "scent": ["향기"],
  "dawn": ["새벽"],
  "accidentally": ["우연히"],
  "uncover": ["드러내다", "밝혀내다"],
  "clarify": ["분명히 하다"],
  "investigate": ["조사하다"],
  "mission": ["임무"],
  "brochure": ["소책자", "안내서"],
  "remote": ["먼", "원격의"],
  "prone": ["~하기 쉬운"],
  "tremendous": ["엄청난"],
  "widespread": ["널리 퍼진"],
  "evil": ["악한", "악"],
  "section": ["부분", "구역"],
  "toss": ["던지다"],
  "relevant": ["관련 있는"],
  "trigger": ["촉발하다", "방아쇠"],
  "cease": ["중단하다"],
  "confront": ["직면하다", "맞서다"],
  "domain": ["영역", "도메인"],
  "impose": ["부과하다", "강요하다"],
  "supreme": ["최고의"],
  "subscribe": ["구독하다", "가입하다"],
  "passage": ["통로", "구절"],
  "frown": ["눈살을 찌푸리다", "찌푸린 표정"],
  "circulate": ["순환하다", "퍼지다"],
  "whereas": ["반면에"],
  "neglect": ["소홀히 하다", "방치하다"],
  "chaos": ["혼란"],
  "sweep": ["쓸다", "휩쓸다"],
  "renowned": ["유명한"],
  "elevate": ["높이다"],
  "adhere": ["고수하다", "달라붙다"],
  "fake": ["가짜의", "위조하다"],
  "extent": ["정도", "범위"],
  "exceptional": ["예외적인", "뛰어난"],
  "capacity": ["수용력", "능력"],
  "merit": ["가치", "장점"],
  "contend": ["주장하다", "다투다"],
  "notify": ["알리다"],
  "infinite": ["무한한"],
  "eternal": ["영원한"],
  "chase": ["쫓다"],
  "crawl": ["기어가다"],
  "poisonous": ["독이 있는"],
  "drastic": ["과감한", "극단적인"],
  "compensate": ["보상하다"],
  "derive": ["얻다", "유래하다"],
  "deprive": ["빼앗다"],
  "vivid": ["생생한"],
  "depict": ["묘사하다"],
  "blend": ["섞다", "조화시키다"],
  "era": ["시대"],
  "install": ["설치하다"],
  "reinforce": ["강화하다"],
  "vast": ["광대한"],
  "refine": ["정제하다", "다듬다"],
  "filter": ["걸러내다", "여과기"],
  "impulse": ["충동"],
  "flexible": ["유연한"],
  "voluntary": ["자발적인"],
  "compulsory": ["의무적인"],
  "blur": ["흐릿해지다"],
  "mislead": ["오도하다", "잘못 이끌다"],
  "collapse": ["붕괴하다", "무너지다"],
  "substantial": ["상당한", "실질적인"],
  "enrich": ["풍부하게 하다"],
  "mutual": ["상호의"],
  "controversy": ["논란"],
  "oblige": ["의무를 지우다", "강요하다"],
  "polish": ["닦다", "윤을 내다"],
  "apt": ["~하기 쉬운", "적절한"],
  "pierce": ["꿰뚫다"],
  "fierce": ["사나운", "격렬한"],
  "cue": ["신호", "단서"],
  "crucial": ["중대한"],
  "convey": ["전달하다"],
  "grasp": ["꽉 잡다", "이해하다"],
  "dense": ["빽빽한", "밀집한"],
  "endure": ["견디다"],
  "utmost": ["최대한의"],
  "mediate": ["중재하다"],
  "intermediate": ["중간의", "중급의"],
  "interchange": ["교환하다", "교차점"],
  "revive": ["되살리다"],
  "boundary": ["경계"],
  "hinder": ["방해하다"],
  "readily": ["기꺼이", "쉽게"],
  "glimpse": ["흘끗 보다", "얼핏 봄"],
  "vibrate": ["진동하다"],
  "float": ["뜨다", "떠다니다"],
  "induce": ["유발하다"],
  "incline": ["기울다", "~하는 경향이 있다"],
  "orient": ["방향을 잡다"],
  "exaggerate": ["과장하다"],
  "eligible": ["자격이 있는"],
  "bulk": ["대량", "부피"],
  "retain": ["유지하다", "보유하다"],
  "restrain": ["억제하다"],
  "curse": ["저주하다", "저주"],
  "flaw": ["결점"],
  "misuse": ["오용하다", "오용"],
  "shatter": ["산산조각 내다"],
  "boost": ["증진시키다"],
  "incorporate": ["포함하다", "법인화하다"],
  "embody": ["구현하다", "상징하다"],
  "probable": ["가능성 있는"],
  "entitle": ["자격을 주다", "제목을 붙이다"],
  "withstand": ["견디다"],
  "straightforward": ["간단한", "솔직한"],
  "fatal": ["치명적인"],
  "innate": ["타고난"],
  "sequence": ["연속", "순서"],
  "scope": ["범위"],
  "disclose": ["드러내다", "공개하다"],
  "discern": ["식별하다"],
  "cling": ["달라붙다"],
  "drift": ["표류하다", "경향"],
  "swift": ["빠른"],
  "accord": ["일치", "일치하다"],
  "seal": ["봉하다", "봉인"],
  "compile": ["편집하다", "수집하다"],
  "convention": ["관습", "회의"],
  "extinguish": ["끄다", "없애다"],
  "momentary": ["순간적인"],
  "endeavor": ["노력", "노력하다"],
  "beware": ["조심하다"],
  "foretell": ["예언하다"],
  "partial": ["부분적인", "편파적인"],
  "rot": ["썩다"],
  "evoke": ["불러일으키다"],
  "sway": ["흔들다", "흔들리다"],
  "collide": ["충돌하다"],
  "strain": ["긴장", "부담"],
  "cluster": ["무리", "모이다"],
  "clutter": ["어수선하게 하다", "잡동사니"],
  "credible": ["믿을 수 있는"],
  "outweigh": ["~보다 더 중요하다"],
  "imprint": ["새기다", "인상"],
  "proficient": ["능숙한"],
  "glow": ["빛나다", "빛"],
  "assert": ["주장하다"],
  "affirm": ["확언하다"],
  "allot": ["할당하다"],
  "loose": ["느슨한"],
  "vulnerable": ["취약한"],
  "drown": ["익사하다"],
  "bare": ["맨몸의", "드러내다"],
  "strip": ["벗기다", "제거하다"],
  "categorize": ["분류하다"],
  "dwindle": ["점점 줄어들다"],
  "retrieve": ["되찾다", "회수하다"],
  "retreat": ["후퇴하다", "후퇴"],
  "undo": ["원상태로 돌리다"],
  "unfold": ["펼치다", "전개되다"],
  "peculiar": ["이상한", "특유의"],
  "halt": ["멈추다", "중단"],
  "precede": ["선행하다", "앞서다"],
  "coincidence": ["우연의 일치"],
  "majestic": ["장엄한"],
  "initiative": ["주도권"],
  "dispense": ["나누어 주다", "없애다"],
  "recess": ["휴식 시간", "움푹한 곳"],
  "seize": ["붙잡다"],
  "sole": ["유일한", "발바닥"],
  "hollow": ["속이 빈"],
  "shrug": ["어깨를 으쓱하다"],
  "tremble": ["떨다"],
  "spatial": ["공간의"],
  "panel": ["패널", "위원단"],
  "flip": ["휙 뒤집다"],
  "flee": ["달아나다"],
  "enclose": ["둘러싸다", "동봉하다"],
  "thrive": ["번영하다"],
  "elaborate": ["정교한", "자세히 설명하다"],
  "drain": ["배수하다", "소모시키다"],
  "arbitrary": ["임의의"],
  "provoke": ["유발하다", "화나게 하다"],
  "intact": ["손상되지 않은"],
  "trivial": ["사소한"],
  "perish": ["죽다", "소멸하다"],
  "pledge": ["맹세", "약속하다"],
  "deficient": ["부족한"],
  "penetrate": ["관통하다", "침투하다"],
  "seemingly": ["겉보기에"],
  "confine": ["제한하다", "가두다"],
  "yearn": ["갈망하다"],
  "exemplify": ["예시하다", "전형적으로 보여주다"],
  "competent": ["유능한"],
  "equivalent": ["동등한", "동등한 것"],
  "linger": ["오래 남다"],
  "align": ["정렬하다", "일치시키다"],
  "gear": ["장비", "기어"],
  "inability": ["무능력"],
  "obscure": ["모호한", "잘 알려지지 않은"],
  "distort": ["왜곡하다"],
  "overload": ["과부하를 주다", "과부하"],
  "oversee": ["감독하다"],
  "overtake": ["추월하다"],
  "undertake": ["떠맡다"],
  "spontaneous": ["자발적인"],
  "simultaneously": ["동시에"],
  "reconciliation": ["화해"],
  "doom": ["파멸시키다", "파멸"],
  "lateral": ["측면의"],
  "criterion": ["기준"],
  "bulletin": ["회보", "게시"],
  "blueprint": ["청사진", "설계도"],
  "norm": ["규범"],
  "coordinate": ["조정하다", "좌표"],
  "accelerate": ["가속하다"],
  "tackle": ["다루다", "맞서다"],
  "coexist": ["공존하다"],
  "misfortune": ["불운"],
  "suppress": ["억압하다", "억제하다"],
  "surpass": ["능가하다"],
  "explicit": ["명백한", "분명한"],
  "posture": ["자세"],
  "marked": ["두드러진"],
  "subsequent": ["그 이후의"],
  "surrender": ["항복하다", "넘겨주다"],
  "precaution": ["예방책"],
  "compel": ["강요하다"],
  "inborn": ["타고난"],
  "segment": ["부분", "나누다"],
  "upright": ["똑바른", "정직한"],
  "illuminate": ["비추다", "밝히다"],
  "rust": ["녹", "녹슬다"],
  "rub": ["문지르다"],
  "scrub": ["문질러 씻다"],
  "falsify": ["위조하다", "거짓으로 만들다"],
  "amplify": ["증폭하다", "확대하다"],
  "magnify": ["확대하다"],
  "magnificent": ["웅장한", "훌륭한"],
  "degrade": ["저하시키다", "비하하다"],
  "vain": ["헛된", "허영심이 강한"],
  "stumble": ["비틀거리다", "우연히 발견하다"],
  "stride": ["성큼성큼 걷다"],
  "disharmony": ["불화", "부조화"],
  "firsthand": ["직접의"],
  "parallel": ["평행한", "유사한"],
  "obstruct": ["막다", "방해하다"],
  "constraint": ["제약"],
  "counterpart": ["상대방", "대응물"],
  "undoubtedly": ["의심할 여지 없이"],
  "mighty": ["강력한"],
  "prompt": ["신속한", "촉발하다"],
  "multitask": ["동시에 여러 일을 하다"],
  "fraction": ["부분", "분수"],
  "prominent": ["두드러진"],
  "sustain": ["유지하다", "지탱하다"],
  "deem": ["여기다", "간주하다"],
  "inherent": ["내재된"],
  "adverse": ["불리한", "해로운"],
  "drawback": ["단점"],
  "phase": ["단계", "국면"],
  "entrust": ["맡기다"],
  "empower": ["권한을 부여하다"],
  "unveil": ["공개하다"],
  "manifest": ["나타내다", "명백한"],
  "advent": ["도래", "출현"],
  "contradict": ["모순되다", "반박하다"],
  "interval": ["간격"],
  "superficial": ["표면적인"],
  "immense": ["엄청난"],
  "hazard": ["위험"],
  "exert": ["가하다", "행사하다"],
  "disguise": ["변장하다", "감추다"],
  "passerby": ["지나가는 사람"],
  "comprise": ["구성하다"],
  "encompass": ["포함하다"],
  "deed": ["행위", "업적"],
  "transition": ["전환", "변천"],
  "shortcoming": ["단점"],
  "sturdy": ["튼튼한"],
  "disrupt": ["방해하다", "붕괴시키다"],
  "compatible": ["양립할 수 있는", "호환되는"],
  "anonymous": ["익명의"],
  "notable": ["주목할 만한"],
  "breakthrough": ["돌파구", "획기적 발전"],
  "prolong": ["연장하다"],
  "terminate": ["끝내다"],
  "sheer": ["순전한", "가파른"],
  "verify": ["검증하다"],
  "mimic": ["흉내 내다"],
  "sneak": ["살금살금 가다"],
  "frontier": ["국경", "개척지"],
  "scheme": ["계획", "음모"],
  "manipulate": ["조작하다"],
  "indulge": ["빠지다", "마음껏 하게 하다"],
  "recipient": ["수령인"],
  "tactic": ["전술"],
  "outgrow": ["더 커져서 맞지 않게 되다", "극복하다"],
  "outset": ["착수", "시작"],
  "fabulous": ["멋진", "엄청난"],
  "plunge": ["뛰어들다", "급락하다"],
  "uphold": ["지지하다", "유지하다"],
  "notorious": ["악명 높은"],
  "lure": ["유혹하다", "유혹물"],
  "trim": ["다듬다"],
  "prestigious": ["명망 있는"],
  "pervade": ["만연하다", "스며들다"],
  "craving": ["갈망"],
  "liable": ["~하기 쉬운", "책임 있는"],
  "comply": ["따르다", "준수하다"],
  "constitute": ["구성하다"],
  "milestone": ["이정표", "획기적 사건"],
  "animate": ["생기를 불어넣다", "생기 있는"],
  "underestimate": ["과소평가하다"],
  "consent": ["동의하다", "동의"],
  "dissent": ["반대하다", "반대"],
  "entity": ["실체", "독립체"],
  "integral": ["필수적인"],
  "divert": ["전환하다", "다른 데로 돌리다"],
  "recur": ["재발하다", "되풀이되다"],
  "configuration": ["구성", "배치"],
  "evade": ["피하다"],
  "erect": ["세우다"],
  "foremost": ["가장 중요한", "가장 앞선"],
  "haunt": ["늘 따라다니다", "출몰하다"],
  "lurk": ["숨어 있다"],
  "browse": ["훑어보다", "둘러보다"],
  "array": ["배열", "다양하게 갖추다"],
  "nuance": ["뉘앙스"],
  "nuisance": ["성가신 것"],
  "intrigue": ["흥미를 돋우다", "음모"],
  "potent": ["강력한"],
  "overflow": ["넘치다"],
  "overturn": ["뒤집다", "전복시키다"],
  "ambiguous": ["애매한"],
  "patch": ["조각", "덧대다"],
  "patriot": ["애국자"],
  "stale": ["신선하지 않은", "진부한"],
  "blast": ["폭발", "폭파하다"],
  "feat": ["위업"],
  "ingenuity": ["독창성", "재주"],
  "beside": ["~옆에"],
  "besides": ["게다가"],
  "alley": ["골목"],
  "ally": ["동맹", "동맹을 맺다"],
  "sociable": ["사교적인"],
  "misplace": ["잘못 두다"],
  "displace": ["옮겨 놓다", "대체하다"],
  "abroad": ["해외에"],
  "imaginative": ["상상력이 풍부한"],
  "imaginary": ["상상의"],
  "imagery": ["심상", "이미지"],
  "respective": ["각각의"],
  "confidential": ["기밀의"],
  "crash": ["충돌하다", "폭락하다"],
  "lay": ["놓다"],
  "lie": ["눕다", "거짓말하다"],
  "alternative": ["대안", "대안의"],
  "alternate": ["번갈아 하다", "번갈아 일어나는"],
  "compliment": ["칭찬", "칭찬하다"],
  "temporal": ["시간의", "일시적인"],
  "submit": ["제출하다", "굴복하다"],
  "marvel": ["경이로워하다", "경이"],
  "row": ["줄", "노 젓다"],
  "memorial": ["기념의", "기념물"],
  "memorable": ["기억할 만한"],
  "lick": ["핥다"],
  "ethical": ["윤리적인"],
  "economical": ["경제적인", "절약하는"],
  "sow": ["씨를 뿌리다"],
  "sew": ["바느질하다"],
  "altitude": ["고도"],
  "aptitude": ["적성", "소질"],
  "migrate": ["이주하다"],
  "emigrate": ["이민 가다"],
  "arise": ["발생하다", "일어나다"],
  "arouse": ["불러일으키다"],
  "simulate": ["모의실험하다", "가장하다"],
  "stimulate": ["자극하다"],
  "through": ["통하여", "통과하여"],
  "wonder": ["궁금해하다", "경이"],
  "considerate": ["사려 깊은"],
  "considerable": ["상당한"],
  "personnel": ["인원", "직원"],
  "royal": ["왕실의"],
  "successful": ["성공한"],
  "successive": ["연속적인"],
  "attach": ["붙이다"],
  "detach": ["분리하다"],
  "discreet": ["신중한", "조심스러운"],
  "discrete": ["별개의"],
  "literary": ["문학의"],
  "literate": ["읽고 쓸 줄 아는"],
  "expire": ["만료되다", "죽다"],
  "aspire": ["열망하다"],
  "exhibit": ["전시하다", "드러내다"],
  "inhibit": ["억제하다"],
  "inhabit": ["살다", "거주하다"],
  "eminent": ["저명한"],
  "imminent": ["임박한"],
  "sensible": ["분별 있는", "합리적인"],
  "sensory": ["감각의"],
  "stationary": ["움직이지 않는"],
  "stationery": ["문구류"],
  "vanish": ["사라지다"],
  "banish": ["추방하다"],
  "conform": ["따르다", "순응하다"],
  "attribute": ["속성", "~의 탓으로 돌리다"],
  "worthless": ["가치 없는"],
  "priceless": ["매우 귀중한"],
  "valueless": ["가치 없는"],
  "invaluable": ["매우 귀중한"],
  "famine": ["기근"],
  "feminine": ["여성의"],
  "fertile": ["비옥한", "다산의"],
  "futile": ["헛된"],
  "acclaim": ["갈채", "환호하다"],
  "exclaim": ["외치다"],
  "proclaim": ["선포하다"],
  "reclaim": ["되찾다"],
  "diploma": ["졸업장"],
  "diplomat": ["외교관"],
  "morale": ["사기"],
  "last": ["지속되다", "마지막의"],
  "present": ["현재의", "제시하다"],
  "fit": ["맞다", "건강한"],
  "board": ["판자", "타다"],
  "fix": ["고치다", "고정하다"],
  "note": ["메모", "주목하다"],
  "force": ["힘", "강요하다"],
  "degree": ["정도", "학위"],
  "fine": ["좋은", "벌금"],
  "stand": ["서다", "입장"],
  "object": ["물건", "반대하다"],
  "interest": ["흥미", "이자"],
  "meet": ["만나다", "충족시키다"],
  "party": ["정당", "파티"],
  "current": ["현재의", "흐름"],
  "spot": ["장소", "발견하다"],
  "project": ["계획", "투영하다"],
  "capital": ["수도", "자본"],
  "state": ["상태", "진술하다"],
  "ground": ["땅", "근거"],
  "cast": ["던지다", "출연진"],
  "tip": ["끝", "조언"],
  "decline": ["감소하다", "거절하다"],
  "suit": ["정장", "적합하다"],
  "mean": ["의미하다", "비열한"],
  "means": ["수단"],
  "meaning": ["의미"],
  "manage": ["관리하다", "해내다"],
  "succeed": ["성공하다", "뒤를 잇다"],
  "appreciate": ["감사하다", "진가를 알다"],
  "bound": ["묶인", "~행의"],
  "bear": ["곰", "견디다"],
  "conduct": ["수행하다", "행동"],
  "reserve": ["예약하다", "보유하다"],
  "direct": ["직접의", "지시하다"],
  "fair": ["공정한", "박람회"],
  "odd": ["이상한", "홀수의"],
  "address": ["주소", "다루다"],
  "even": ["심지어", "짝수의"],
  "flat": ["평평한", "아파트"],
  "branch": ["가지", "지점"],
  "sentence": ["문장", "선고하다"],
  "drive": ["운전하다", "몰아가다"],
  "discharge": ["방출하다", "퇴원시키다"],
  "stroke": ["치기", "뇌졸중"],
  "commission": ["위원회", "수수료"],
  "vessel": ["선박", "그릇"],
  "manual": ["수동의", "안내서"],
  "correspond": ["일치하다", "서신을 주고받다"],
  "company": ["회사", "동행"],
  "suspend": ["중단하다", "매달다"],
  "issue": ["문제", "발행하다"],
  "treat": ["대하다", "대접"],
  "order": ["주문", "질서"],
  "bar": ["막다", "막대"],
  "deposit": ["예금", "맡기다"],
  "conceive": ["상상하다", "임신하다"],
  "dictate": ["지시하다", "받아쓰게 하다"],
  "plot": ["줄거리", "음모를 꾸미다"],
  "bother": ["귀찮게 하다", "신경 쓰다"],
  "pitch": ["던지다", "음높이"],
  "lean": ["기울다", "마른"],
  "host": ["주최하다", "주인"],
  "yield": ["산출하다", "양보하다"],
  "post": ["게시하다", "우편"],
  "converse": ["대화하다", "반대의"],
  "profile": ["옆모습", "프로필"],
  "delight": ["기쁨", "매우 기쁘게 하다"],
  "rejoice": ["기뻐하다"],
  "agreeable": ["기분 좋은", "동의하는"],
  "impress": ["인상을 주다"],
  "awe": ["경외감"],
  "enchant": ["매혹하다"],
  "grin": ["싱긋 웃다", "활짝 웃음"],
  "solitude": ["고독"],
  "sorrow": ["슬픔"],
  "grief": ["비탄"],
  "distress": ["고통", "괴롭히다"],
  "gloomy": ["우울한", "어두운"],
  "depress": ["우울하게 하다"],
  "lament": ["한탄하다", "한탄"],
  "mourn": ["애도하다"],
  "moan": ["신음하다", "신음"],
  "groan": ["신음하다", "신음"],
  "sob": ["흐느껴 울다"],
  "weep": ["울다"],
  "pity": ["동정", "안타까운 일"],
  "compassion": ["연민"],
  "sympathy": ["동정", "공감"],
  "empathy": ["공감"],
  "console": ["위로하다", "콘솔"],
  "reassure": ["안심시키다"],
  "affection": ["애정"],
  "hatred": ["증오"],
  "disgust": ["혐오감", "역겹게 하다"],
  "envy": ["부러워하다", "부러움"],
  "hostile": ["적대적인"],
  "sentiment": ["감정", "정서"],
  "outburst": ["폭발", "분출"],
  "nostalgia": ["향수"],
  "boredom": ["지루함"],
  "dull": ["지루한", "둔한"],
  "tedious": ["지루한"],
  "irritate": ["짜증 나게 하다"],
  "upset": ["속상하게 하다", "속상한"],
  "furious": ["몹시 화가 난"],
  "rage": ["격노", "격노하다"],
  "outrage": ["분노", "격분하게 하다"],
  "resent": ["분개하다"],
  "panic": ["공황", "당황하다"],
  "dread": ["두려워하다", "공포"],
  "terrify": ["겁먹게 하다"],
  "intimidate": ["겁주다"],
  "startle": ["깜짝 놀라게 하다"],
  "astounding": ["놀라운"],
  "stun": ["기절시키다", "놀라게 하다"],
  "puzzle": ["수수께끼", "당황하게 하다"],
  "perplex": ["당혹하게 하다"],
  "dismay": ["실망", "낙담하게 하다"],
  "overwhelm": ["압도하다"],
  "awkward": ["어색한"],
  "humiliate": ["굴욕감을 주다"],
  "flush": ["붉어지다", "물을 내리다"],
  "stance": ["입장", "자세"],
  "elegant": ["우아한"],
  "sophisticated": ["세련된", "정교한"],
  "decent": ["괜찮은", "품위 있는"],
  "dignity": ["존엄"],
  "earnest": ["진지한"],
  "integrity": ["정직성", "완전성"],
  "virtue": ["미덕"],
  "goodwill": ["호의"],
  "courtesy": ["예의"],
  "hospitality": ["환대"],
  "gratitude": ["감사"],
  "merciful": ["자비로운"],
  "generous": ["관대한"],
  "tolerate": ["참다", "용인하다"],
  "humble": ["겸손한"],
  "trustworthy": ["믿을 만한"],
  "thoughtful": ["사려 깊은"],
  "mindful": ["유념하는"],
  "alert": ["경계하는", "경보"],
  "reckless": ["무모한"],
  "hasten": ["재촉하다", "서두르다"],
  "enthusiasm": ["열정"],
  "passionate": ["열정적인"],
  "keen": ["예리한", "열망하는"],
  "willing": ["기꺼이 하는"],
  "pessimistic": ["비관적인"],
  "skeptical": ["회의적인"],
  "cynical": ["냉소적인"],
  "sarcastic": ["비꼬는"],
  "indifferent": ["무관심한"],
  "reluctant": ["마지못해 하는"],
  "hesitate": ["주저하다"],
  "obedient": ["순종하는"],
  "receptive": ["잘 받아들이는"],
  "naive": ["순진한"],
  "clumsy": ["서투른"],
  "tact": ["재치", "요령"],
  "cowardly": ["겁 많은"],
  "timid": ["소심한"],
  "bold": ["대담한"],
  "dare": ["감히 ~하다"],
  "outgoing": ["외향적인"],
  "extrovert": ["외향적인 사람"],
  "candid": ["솔직한"],
  "outspoken": ["거침없이 말하는"],
  "decisive": ["결단력 있는"],
  "stubborn": ["고집 센"],
  "rigid": ["딱딱한", "엄격한"],
  "strict": ["엄격한"],
  "stern": ["엄한"],
  "solemn": ["엄숙한"],
  "mischief": ["장난", "해악"],
  "wicked": ["사악한"],
  "nasty": ["못된", "불쾌한"],
  "tease": ["놀리다"],
  "mock": ["조롱하다"],
  "ridicule": ["비웃다", "조롱"],
  "flatter": ["아첨하다"],
  "self-esteem": ["자존감"],
  "disregard": ["무시하다", "무시"],
  "despise": ["경멸하다"],
  "scorn": ["경멸", "경멸하다"],
  "contempt": ["경멸"],
  "betray": ["배신하다"],
  "cruel": ["잔인한"],
  "brutal": ["잔혹한"],
  "savage": ["야만적인", "사나운"],
  "vicious": ["사악한", "악순환의"],
  "insane": ["미친"],
  "psychology": ["심리학"],
  "mental": ["정신의"],
  "conscious": ["의식하는", "의식이 있는"],
  "subconscious": ["잠재의식의"],
  "ego": ["자아"],
  "intuition": ["직관"],
  "instinct": ["본능"],
  "perceive": ["지각하다"],
  "presume": ["추정하다"],
  "infer": ["추론하다"],
  "speculate": ["추측하다", "사색하다"],
  "ponder": ["곰곰이 생각하다"],
  "contemplate": ["숙고하다"],
  "meditate": ["명상하다"],
  "envision": ["상상하다"],
  "viewpoint": ["관점"],
  "perspective": ["관점", "원근법"],
  "outlook": ["전망", "태도"],
  "notion": ["개념", "생각"],
  "dilemma": ["딜레마", "진퇴양난"],
  "rational": ["합리적인"],
  "coherent": ["일관성 있는"],
  "intrinsic": ["본질적인"],
  "ideology": ["이데올로기"],
  "radical": ["급진적인"],
  "stereotype": ["고정관념"],
  "bias": ["편견"],
  "misconception": ["오해"],
  "obsess": ["사로잡다"],
  "preoccupy": ["마음을 빼앗다"],
  "spice": ["향신료", "양념하다"],
  "sour": ["신맛의", "시큼한"],
  "edible": ["먹을 수 있는"],
  "intake": ["섭취량"],
  "devour": ["게걸스럽게 먹다"],
  "feast": ["잔치", "실컷 먹다"],
  "shelter": ["피난처", "보호하다"],
  "reside": ["거주하다"],
  "dwell": ["살다"],
  "adjacent": ["인접한"],
  "rent": ["임대료", "빌리다"],
  "lease": ["임대하다", "임대차 계약"],
  "tenant": ["세입자"],
  "renovate": ["수리하다", "개조하다"],
  "furnish": ["비치하다", "가구를 들여놓다"],
  "ventilate": ["환기시키다"],
  "spacious": ["넓은"],
  "cozy": ["아늑한"],
  "garment": ["의복"],
  "outfit": ["복장", "장비"],
  "costume": ["의상", "분장"],
  "ornament": ["장식품", "장식하다"],
  "cosmetic": ["화장품", "미용의"],
  "thread": ["실"],
  "texture": ["질감"],
  "fabric": ["천", "직물"],
  "tailor": ["재단사", "맞추다"],
  "weave": ["짜다"],
  "detergent": ["세제"],
  "laundry": ["세탁물", "세탁소"],
  "errand": ["심부름"],
  "utensil": ["도구", "가정용품"],
  "wrench": ["렌치", "비틀다"],
  "carriage": ["마차", "객차"],
  "compartment": ["칸", "구획"],
  "fare": ["요금"],
  "toll": ["통행료"],
  "intersection": ["교차로"],
  "pedestrian": ["보행자", "보행자의"],
  "bypass": ["우회하다", "우회로"],
  "congestion": ["혼잡"],
  "depart": ["출발하다"],
  "shipping": ["선적", "해운"],
  "cabin": ["객실", "오두막"],
  "crew": ["승무원", "팀"],
  "canal": ["운하"],
  "navigate": ["길을 찾다", "항해하다"],
  "steer": ["조종하다", "이끌다"],
  "dock": ["부두", "배를 대다"],
  "paddle": ["노", "노를 젓다"],
  "recreation": ["오락", "휴양"],
  "trail": ["오솔길", "자취"],
  "exotic": ["이국적인"],
  "spectacular": ["장관의", "화려한"],
  "souvenir": ["기념품"],
  "jetlag": ["시차 피로"],
  "accommodate": ["수용하다", "편의를 도모하다"],
  "roam": ["돌아다니다"],
  "interpersonal": ["대인 관계의"],
  "bond": ["유대", "접착하다"],
  "divorce": ["이혼", "분리하다"],
  "ancestor": ["조상"],
  "offspring": ["자손"],
  "kin": ["친족"],
  "sibling": ["형제자매"],
  "elder": ["연장자", "나이가 많은"],
  "peer": ["또래", "동료"],
  "spouse": ["배우자"],
  "mother-in-law": ["시어머니", "장모"],
  "acquaintance": ["아는 사람"],
  "infant": ["유아"],
  "childhood": ["어린 시절"],
  "adolescent": ["청소년"],
  "youth": ["젊음", "청년"],
  "parental": ["부모의"],
  "maternal": ["어머니의", "모성의"],
  "rear": ["기르다", "뒤쪽"],
  "nurture": ["양육하다", "양육"],
  "foster": ["기르다", "촉진하다"],
  "orphan": ["고아"],
  "nursery": ["보육원", "육아실"],
  "guidance": ["지도", "안내"],
  "mentor": ["조언자", "멘토"],
  "educational": ["교육의"],
  "institute": ["기관"],
  "faculty": ["교수진", "능력"],
  "scholar": ["학자", "장학생"],
  "pupil": ["학생", "눈동자"],
  "secondary": ["중등의", "부차적인"],
  "curriculum": ["교육 과정"],
  "mastery": ["숙달"],
  "graduate": ["졸업하다", "졸업생"],
  "tuition": ["수업료"],
  "dormitory": ["기숙사"],
  "vocation": ["직업", "천직"],
  "expertise": ["전문 지식"],
  "specialize": ["전문화하다"],
  "novice": ["초보자"],
  "workforce": ["노동력"],
  "department": ["부서", "학과"],
  "recruit": ["모집하다", "신병"],
  "employ": ["고용하다", "사용하다"],
  "executive": ["임원", "집행의"],
  "supervise": ["감독하다"],
  "coworker": ["동료"],
  "commute": ["통근하다", "통근"],
  "incentive": ["장려책", "동기"],
  "janitor": ["관리인", "청소부"],
  "craft": ["기술", "공예"],
  "sculpture": ["조각", "조각품"],
  "pottery": ["도자기"],
  "authentic": ["진짜의", "진정한"],
  "aesthetic": ["미적인"],
  "portray": ["묘사하다"],
  "mold": ["틀", "주형"],
  "carve": ["조각하다"],
  "inscribe": ["새기다", "적다"],
  "masterpiece": ["걸작"],
  "vocal": ["목소리의", "보컬"],
  "tune": ["곡조", "조율하다"],
  "lyric": ["가사", "서정시"],
  "repertoire": ["레퍼토리"],
  "choir": ["합창단"],
  "auditorium": ["강당"],
  "rehearse": ["예행연습하다"],
  "verbal": ["말의", "구두의"],
  "oral": ["입의", "구두의"],
  "linguistic": ["언어의"],
  "pronounce": ["발음하다"],
  "utter": ["말하다", "완전한"],
  "translate": ["번역하다"],
  "dialect": ["방언"],
  "fluent": ["유창한"],
  "eloquent": ["웅변의", "달변의"],
  "bilingual": ["2개 국어를 하는"],
  "monologue": ["독백"],
  "phrase": ["구"],
  "paragraph": ["문단"],
  "script": ["대본", "글씨"],
  "manuscript": ["원고"],
  "theme": ["주제"],
  "context": ["맥락"],
  "protagonist": ["주인공"],
  "genre": ["장르"],
  "narrative": ["이야기", "서술의"],
  "novel": ["소설", "새로운"],
  "myth": ["신화"],
  "anecdote": ["일화"],
  "verse": ["운문", "절"],
  "rhyme": ["운율", "운이 맞다"],
  "metaphor": ["은유"],
  "analogy": ["유추", "비유"],
  "irony": ["반어", "아이러니"],
  "paradox": ["역설"],
  "connote": ["함축하다"],
  "riddle": ["수수께끼"],
  "quote": ["인용하다", "인용문"],
  "cite": ["인용하다"],
  "draft": ["초안", "초안을 작성하다"],
  "edit": ["편집하다"],
  "publish": ["출판하다"],
  "comment": ["논평", "논평하다"],
  "sociology": ["사회학"],
  "population": ["인구"],
  "household": ["가정", "가정의"],
  "community": ["공동체", "지역사회"],
  "metropolis": ["대도시"],
  "cosmopolitan": ["세계적인", "국제적인"],
  "gender": ["성별"],
  "equality": ["평등"],
  "discriminate": ["차별하다", "구별하다"],
  "abuse": ["남용하다", "학대"],
  "exploit": ["이용하다", "착취하다"],
  "suicide": ["자살"],
  "paradigm": ["패러다임", "사고방식"],
  "welfare": ["복지"],
  "charity": ["자선"],
  "donate": ["기부하다"],
  "celebrity": ["유명 인사"],
  "publicity": ["홍보", "대중의 관심"],
  "broadcast": ["방송하다", "방송"],
  "coverage": ["보도", "적용 범위"],
  "collective": ["집단의", "집합체"],
  "custom": ["관습", "맞춤"],
  "mainstream": ["주류"],
  "prevail": ["우세하다", "널리 퍼지다"],
  "outdated": ["구식의"],
  "taboo": ["금기"],
  "folk": ["사람들", "민속의"],
  "privilege": ["특권"],
  "slavery": ["노예 제도"],
  "primitive": ["원시의"],
  "aboriginal": ["원주민의"],
  "tribe": ["부족"],
  "nomadic": ["유목의"],
  "historical": ["역사적인"],
  "archaeology": ["고고학"],
  "anthropology": ["인류학"],
  "civilization": ["문명"],
  "originate": ["기원하다"],
  "descend": ["내려오다", "유래하다"],
  "inherit": ["상속하다", "물려받다"],
  "legacy": ["유산"],
  "monument": ["기념물"],
  "commemorate": ["기념하다"],
  "remains": ["유적", "남은 것"],
  "artifact": ["유물"],
  "excavate": ["발굴하다"],
  "prehistoric": ["선사 시대의"],
  "medieval": ["중세의"],
  "dynasty": ["왕조"],
  "lord": ["영주", "주인"],
  "divine": ["신의", "신성한"],
  "spiritual": ["정신의", "영적인"],
  "ritual": ["의식", "의례적인"],
  "sermon": ["설교"],
  "priest": ["성직자"],
  "chant": ["성가", "외우다"],
  "immortal": ["불멸의"],
  "destiny": ["운명"],
  "prophecy": ["예언"],
  "supernatural": ["초자연적인"],
  "politics": ["정치"],
  "authority": ["권위", "권한"],
  "rule": ["규칙", "지배하다"],
  "govern": ["통치하다"],
  "reign": ["통치하다", "통치 기간"],
  "dominate": ["지배하다"],
  "sovereign": ["주권의", "군주"],
  "autonomy": ["자치", "자율성"],
  "regime": ["정권", "체제"],
  "dictatorship": ["독재 정치"],
  "torture": ["고문", "고문하다"],
  "municipal": ["시의", "지방 자치의"],
  "minister": ["장관", "성직자"],
  "nominate": ["지명하다"],
  "vote": ["투표하다", "투표"],
  "ballot": ["투표용지", "투표"],
  "poll": ["여론조사", "투표"],
  "agenda": ["의제"],
  "petition": ["청원서", "청원하다"],
  "slogan": ["구호"],
  "rally": ["집회", "다시 모으다"],
  "rebel": ["반항하다", "반란자"],
  "overthrow": ["전복시키다", "전복"],
  "warfare": ["전쟁"],
  "combat": ["전투", "싸우다"],
  "warrior": ["전사"],
  "spear": ["창"],
  "bullet": ["총알"],
  "military": ["군대의", "군"],
  "martial": ["군사의"],
  "dispatch": ["보내다", "급파"],
  "march": ["행진하다", "행진"],
  "invade": ["침략하다"],
  "fortress": ["요새"],
  "refuge": ["피난처"],
  "delegate": ["대표", "위임하다"],
  "legislation": ["법률", "입법"],
  "enact": ["제정하다"],
  "amend": ["수정하다", "개정하다"],
  "abolish": ["폐지하다"],
  "outlaw": ["불법화하다", "범죄자"],
  "enforce": ["집행하다", "강요하다"],
  "violate": ["위반하다"],
  "justice": ["정의", "사법"],
  "sue": ["고소하다"],
  "attorney": ["변호사"],
  "prosecutor": ["검사"],
  "jury": ["배심원단"],
  "plead": ["간청하다", "변론하다"],
  "witness": ["목격자", "목격하다"],
  "testimony": ["증언"],
  "verdict": ["평결"],
  "conviction": ["확신", "유죄 판결"],
  "condemn": ["비난하다", "선고하다"],
  "execute": ["실행하다", "처형하다"],
  "imprison": ["감옥에 넣다"],
  "offend": ["불쾌하게 하다", "위반하다"],
  "violence": ["폭력"],
  "theft": ["절도"],
  "rob": ["강탈하다"],
  "burglar": ["강도"],
  "kidnap": ["납치하다"],
  "corrupt": ["부패한", "타락시키다"],
  "bribe": ["뇌물", "뇌물을 주다"],
  "fraud": ["사기"],
  "patrol": ["순찰", "순찰하다"],
  "arrest": ["체포하다", "체포"],
  "consume": ["소비하다"],
  "purchase": ["구매하다", "구매"],
  "afford": ["~할 여유가 있다"],
  "refund": ["환불하다", "환불"],
  "exchange": ["교환하다", "교환"],
  "luxury": ["사치", "사치품"],
  "bargain": ["흥정하다", "싼 물건"],
  "thrifty": ["검소한"],
  "commodity": ["상품"],
  "cost": ["비용", "비용이 들다"],
  "expense": ["비용", "지출"],
  "soar": ["급등하다", "치솟다"],
  "inflation": ["인플레이션"],
  "recession": ["경기 침체"],
  "fluctuate": ["변동하다"],
  "monopoly": ["독점"],
  "surplus": ["잉여", "초과"],
  "prosper": ["번영하다"],
  "flourish": ["번성하다"],
  "monetary": ["화폐의"],
  "estate": ["부동산", "재산"],
  "revenue": ["수익"],
  "invest": ["투자하다"],
  "budget": ["예산"],
  "margin": ["여백", "차이"],
  "tax": ["세금", "세금을 부과하다"],
  "bankrupt": ["파산한", "파산시키다"],
  "auction": ["경매", "경매에 부치다"],
  "bid": ["입찰하다", "입찰"],
  "industrial": ["산업의"],
  "infrastructure": ["기반 시설"],
  "machinery": ["기계류"],
  "inventory": ["재고 목록", "재고"],
  "warehouse": ["창고"],
  "corporate": ["기업의"],
  "enterprise": ["기업", "진취성"],
  "merge": ["합병하다"],
  "headquarters": ["본부", "본사"],
  "transaction": ["거래"],
  "marketable": ["잘 팔리는"],
  "merchandise": ["상품", "상품을 판매하다"],
  "wholesale": ["도매의", "도매"],
  "retail": ["소매의", "소매"],
  "vendor": ["행상인", "판매자"],
  "peasant": ["소작농", "농민"],
  "plow": ["쟁기질하다", "쟁기"],
  "irrigation": ["관개"],
  "reservoir": ["저수지"],
  "weed": ["잡초", "잡초를 뽑다"],
  "pesticide": ["농약"],
  "organic": ["유기농의", "유기적인"],
  "ripen": ["익다", "익히다"],
  "grind": ["갈다", "빻다"],
  "dairy": ["유제품의", "낙농업"],
  "livestock": ["가축"],
  "cattle": ["소"],
  "herd": ["떼", "몰다"],
  "pasture": ["목초지", "방목하다"],
  "hay": ["건초"],
  "orchard": ["과수원"],
  "timber": ["목재"],
  "flock": ["떼", "모이다"],
  "burrow": ["굴", "파고들다"],
  "dormant": ["휴면 상태의"],
  "breed": ["번식하다", "품종"],
  "hatch": ["부화하다", "부화"],
  "fur": ["털가죽"],
  "vegetation": ["초목"],
  "stem": ["줄기", "유래하다"],
  "sprout": ["싹트다", "싹"],
  "bud": ["싹", "싹트다"],
  "bloom": ["꽃이 피다", "꽃"],
  "pollen": ["꽃가루"],
  "biological": ["생물학의"],
  "hybrid": ["잡종", "혼합된"],
  "organism": ["유기체"],
  "clone": ["복제하다", "복제물"],
  "evolve": ["진화하다"],
  "mutation": ["돌연변이"],
  "mammal": ["포유류"],
  "primate": ["영장류"],
  "predator": ["포식자"],
  "prey": ["먹이", "사냥하다"],
  "ecology": ["생태학"],
  "rainforest": ["열대우림"],
  "deforestation": ["삼림 벌채"],
  "extinct": ["멸종한"],
  "endanger": ["위태롭게 하다"],
  "soil": ["흙", "토양"],
  "erode": ["침식하다"],
  "barren": ["불모의"],
  "wilderness": ["황야"],
  "twilight": ["황혼"],
  "mist": ["안개"],
  "temperate": ["온화한", "절제하는"],
  "humid": ["습한"],
  "geology": ["지질학"],
  "hemisphere": ["반구"],
  "latitude": ["위도"],
  "equator": ["적도"],
  "peak": ["정점", "절정에 이르다"],
  "plateau": ["고원", "정체기"],
  "tide": ["조수", "흐름"],
  "polar": ["극지의"],
  "arctic": ["북극의"],
  "glacier": ["빙하"],
  "earthquake": ["지진"],
  "erupt": ["분출하다", "폭발하다"],
  "landslide": ["산사태"],
  "drought": ["가뭄"],
  "flood": ["홍수", "범람하다"],
  "catastrophe": ["재앙"],
  "devastate": ["황폐화시키다"],
  "casualty": ["사상자", "피해"],
  "trash": ["쓰레기"],
  "debris": ["잔해"],
  "landfill": ["매립지"],
  "dump": ["버리다", "쓰레기장"],
  "radioactive": ["방사성의"],
  "toxic": ["유독한"],
  "emit": ["배출하다", "내뿜다"],
  "stink": ["악취가 나다", "악취"],
  "contaminate": ["오염시키다"],
  "renewable": ["재생 가능한"],
  "deplete": ["고갈시키다"],
  "experiment": ["실험", "실험하다"],
  "hypothesis": ["가설"],
  "apparatus": ["장치", "기구"],
  "vacuum": ["진공", "진공청소기"],
  "equilibrium": ["평형", "균형"],
  "solid": ["고체의", "단단한"],
  "liquid": ["액체의", "액체"],
  "fluid": ["유동체", "유동적인"],
  "dissolve": ["녹다", "해산하다"],
  "dilute": ["희석하다"],
  "vapor": ["증기"],
  "condense": ["응축하다", "요약하다"],
  "combustion": ["연소"],
  "chemical": ["화학의", "화학 물질"],
  "compound": ["혼합물", "합성하다"],
  "particle": ["입자"],
  "molecule": ["분자"],
  "atom": ["원자"],
  "carbon": ["탄소"],
  "hydrogen": ["수소"],
  "physics": ["물리학"],
  "mass": ["질량", "대량"],
  "gravity": ["중력"],
  "magnet": ["자석"],
  "friction": ["마찰"],
  "elastic": ["탄력 있는"],
  "magnitude": ["크기", "규모"],
  "electronic": ["전자 공학의"],
  "electric": ["전기의"],
  "circuit": ["회로"],
  "spectrum": ["스펙트럼", "범위"],
  "radiate": ["방사하다", "발산하다"],
  "thermal": ["열의"],
  "astronomy": ["천문학"],
  "cosmos": ["우주"],
  "solar": ["태양의"],
  "satellite": ["위성"],
  "telescope": ["망원경"],
  "probe": ["탐사선", "조사하다"],
  "alien": ["외계인", "외국의"],
  "compute": ["계산하다"],
  "subtract": ["빼다"],
  "multiply": ["곱하다", "증가하다"],
  "equate": ["동일시하다"],
  "approximate": ["대략적인", "근사치"],
  "formula": ["공식"],
  "arithmetic": ["산수"],
  "numerical": ["수치의"],
  "numerous": ["수많은"],
  "maximum": ["최대의", "최대"],
  "minimize": ["최소화하다"],
  "statistics": ["통계학", "통계 자료"],
  "gross": ["총의", "엄청난"],
  "ratio": ["비율"],
  "proportion": ["비율"],
  "variable": ["변수", "변하기 쉬운"],
  "correlation": ["상관관계"],
  "geometry": ["기하학"],
  "linear": ["직선의"],
  "curve": ["곡선", "굽다"],
  "spiral": ["나선형의", "나선"],
  "sphere": ["구", "영역"],
  "oval": ["타원형의", "타원"],
  "dimension": ["차원", "크기"],
  "length": ["길이"],
  "diameter": ["지름"],
  "anatomy": ["해부학", "구조"],
  "physiology": ["생리학"],
  "spine": ["척추"],
  "skull": ["두개골"],
  "limb": ["팔다리"],
  "forehead": ["이마"],
  "beard": ["수염"],
  "corpse": ["시체"],
  "organ": ["기관", "장기"],
  "tissue": ["조직", "티슈"],
  "flesh": ["살"],
  "vein": ["정맥", "맥"],
  "nerve": ["신경", "배짱"],
  "neural": ["신경의"],
  "sensation": ["감각", "돌풍"],
  "sight": ["시력", "보기"],
  "naked": ["벌거벗은"],
  "auditory": ["청각의"],
  "pulse": ["맥박"],
  "breathe": ["숨 쉬다"],
  "respiration": ["호흡"],
  "inhale": ["들이마시다"],
  "perspire": ["땀 흘리다"],
  "motor": ["운동의", "모터"],
  "athletic": ["운동의"],
  "gymnastics": ["체조"],
  "sprint": ["전력 질주", "전력 질주하다"],
  "metabolism": ["신진대사"],
  "diet": ["식단", "다이어트하다"],
  "nourish": ["영양을 공급하다"],
  "slim": ["날씬한"],
  "obesity": ["비만"],
  "longevity": ["장수"],
  "hygiene": ["위생"],
  "sanitation": ["위생", "공중보건"],
  "weary": ["지친"],
  "fatigue": ["피로", "피로하게 하다"],
  "shiver": ["떨다", "전율"],
  "sneeze": ["재채기하다", "재채기"],
  "choke": ["질식시키다", "숨이 막히다"],
  "bruise": ["멍", "멍이 들게 하다"],
  "sprain": ["삐다", "접질리다"],
  "swell": ["붓다", "팽창하다"],
  "inflame": ["염증을 일으키다", "격분시키다"],
  "sore": ["아픈", "상처"],
  "allergic": ["알레르기의"],
  "itch": ["가렵다", "가려움"],
  "stiffen": ["뻣뻣해지다"],
  "disabled": ["장애가 있는"],
  "impair": ["손상시키다"],
  "trauma": ["외상", "정신적 충격"],
  "deadly": ["치명적인"],
  "contagious": ["전염성의"],
  "plague": ["전염병", "괴롭히다"],
  "epidemic": ["유행병"],
  "outbreak": ["발발", "발생"],
  "chronic": ["만성적인"],
  "influenza": ["독감"],
  "asthma": ["천식"],
  "diabetes": ["당뇨병"],
  "cure": ["치료하다", "치료법"],
  "remedy": ["치료법", "해결책"],
  "soothe": ["진정시키다"],
  "medical": ["의학의"],
  "clinic": ["병원", "진료소"],
  "physician": ["의사"],
  "diagnose": ["진단하다"],
  "surgery": ["수술", "외과"],
  "transplant": ["이식하다", "이식"],
  "pharmacy": ["약국", "약학"],
  "prescribe": ["처방하다"],
  "medication": ["약물", "약"],
  "dose": ["1회분", "투여하다"],
  "painkiller": ["진통제"],
  "antibiotic": ["항생제"],
  "vaccine": ["백신"],
  "inject": ["주사하다", "주입하다"],
  "apart from": ["~을 제외하고"],
  "far from": ["결코 ~이 아닌"],
  "as to": ["~에 관하여"],
  "by far": ["훨씬", "단연"],
  "call for": ["요구하다"],
  "consist of": ["~로 이루어지다"],
  "make up": ["구성하다", "화장"],
  "end up": ["결국 ~하게 되다"],
  "free of": ["~이 없는"],
  "get rid of": ["없애다"],
  "hand in": ["제출하다"],
  "at hand": ["가까이에", "당면한"],
  "in advance": ["미리"],
  "in addition to": ["~에 더하여"],
  "in terms of": ["~의 면에서"],
  "in turn": ["차례로", "결국"],
  "leave out": ["빼놓다"],
  "refer to": ["언급하다", "가리키다"],
  "take on": ["떠맡다", "띠다"],
  "take over": ["인수하다", "장악하다"],
  "take up": ["시작하다", "차지하다"],
  "take care of": ["돌보다"],
  "look for": ["찾다"],
  "in that": ["~라는 점에서"],
  "take place": ["일어나다"],
  "take part in": ["참가하다"],
  "turn out": ["~로 드러나다"],
  "cope with": ["대처하다"],
  "due to": ["~때문에"],
  "result from": ["~에서 비롯되다"],
  "anything but": ["결코 ~이 아닌"],
  "nothing but": ["오직 ~뿐인"],
  "all but": ["거의"],
  "longfor": ["갈망하다"],
  "passaway": ["사망하다"],
  "at once": ["즉시"],
  "bring out": ["드러내다", "출판하다"],
  "bring up": ["기르다", "언급하다"],
  "build up": ["축적", "증가"],
  "carry on": ["계속하다"],
  "a series of": ["일련의"],
  "account for": ["설명하다", "차지하다"],
  "along with": ["~와 함께"],
  "catch up with": ["따라잡다"],
  "keep up with": ["따라가다"],
  "hold on": ["기다리다", "붙잡다"],
  "in charge of": ["~을 담당하는"],
  "in the face of": ["~에 직면하여"],
  "in itself": ["그 자체로"],
  "in place": ["제자리에", "시행 중인"],
  "workout": ["운동", "해결되다"],
  "wear out": ["닳게 하다", "지치게 하다"],
  "keep in mind": ["명심하다"],
  "layout": ["배치", "설계"],
  "set out": ["출발하다", "시작하다"],
  "set aside": ["따로 떼어 두다"],
  "have nothing to do with": ["~와 관계가 없다"],
  "have something to do with": ["~와 관계가 있다"],
  "payoff": ["성과", "보수"],
  "pickout": ["골라내다"],
  "take": ["가지다", "데려가다"],
  "take in": ["받아들이다", "속이다"],
  "on behalf of": ["~을 대신하여"],
  "for the sake of": ["~을 위해서"],
  "advocate": ["지지하다", "옹호자"],
  "entail": ["수반하다"],
  "withhold": ["보류하다", "억누르다"],
  "dispute": ["논쟁하다", "논쟁"],
  "intervene": ["개입하다"],
  "roar": ["포효하다", "으르렁거리다"],
  "refrain": ["자제하다", "후렴"],
  "embed": ["깊이 박다", "내재시키다"],
  "immerse": ["담그다", "몰두시키다"],
  "setback": ["좌절", "차질"],
  "entangle": ["얽히게 하다"],
  "tangible": ["만질 수 있는", "분명한"],
  "enlighten": ["깨우치게 하다"],
  "inflict": ["가하다"],
  "incur": ["초래하다", "입다"],
  "legitimate": ["합법적인", "정당한"],
  "render": ["만들다", "제공하다"],
  "realm": ["영역", "왕국"],
  "terrain": ["지형"],
  "discourse": ["담론", "담화"],
  "improvise": ["즉흥적으로 하다"],
  "patron": ["후원자", "단골손님"],
  "crude": ["조잡한", "원유의"],
  "imperative": ["필수적인", "명령"],
  "plausible": ["그럴듯한"],
  "slaughter": ["도살하다", "학살"],
  "spur": ["박차를 가하다", "자극"],
  "stroll": ["산책하다", "산책"],
  "surge": ["급증하다", "급증"],
  "defy": ["거역하다", "무시하다"],
  "duplicate": ["복제하다", "복제품"],
  "synthetic": ["합성의", "인공의"],
  "susceptible": ["민감한", "취약한"],
  "counteract": ["상쇄하다"],
  "counterattack": ["반격하다", "반격"],
  "rigorous": ["엄격한", "철저한"],
  "vigorous": ["활기찬", "격렬한"],
  "insomnia": ["불면증"],
  "ascend": ["오르다"],
  "solidarity": ["연대"],
  "wither": ["시들다"],
  "predominant": ["지배적인"],
  "preliminary": ["예비의"],
  "predecessor": ["전임자", "선배"],
  "demolish": ["철거하다", "뒤집어엎다"],
  "alleviate": ["완화하다"],
  "aggravate": ["악화시키다"],
  "deterioration": ["악화"],
  "afflict": ["괴롭히다"],
  "peril": ["위험"],
  "compress": ["압축하다"],
  "segregation": ["분리", "차별 분리"],
  "hierarchy": ["계층", "위계"],
  "salient": ["두드러진"],
  "subordinate": ["부하", "종속된"],
  "diffusion": ["확산"],
  "disperse": ["흩어지게 하다", "분산시키다"],
  "converge": ["한 점으로 모이다"],
  "shred": ["갈기갈기 찢다", "조각"],
  "adorn": ["장식하다"],
  "adore": ["몹시 좋아하다"],
  "benevolent": ["자비로운"],
  "altruism": ["이타주의"],
  "imprudent": ["현명하지 못한", "경솔한"],
  "subside": ["가라앉다"],
  "submerge": ["잠수시키다", "잠기다"],
  "subdue": ["진압하다", "약화시키다"],
  "transcribe": ["베껴 쓰다", "전사하다"],
  "thrust": ["밀치다", "추진력"],
  "backfire": ["역효과가 나다"],
  "curb": ["억제하다", "연석"],
  "detract": ["손상시키다", "딴 데로 돌리다"],
  "blunt": ["무딘", "직설적인"],
  "alienate": ["소외시키다"],
  "affluent": ["부유한"],
  "indigenous": ["토착의"],
  "consecutive": ["연속적인"],
  "elusive": ["이해하기 어려운", "붙잡기 어려운"],
  "resilient": ["회복력이 있는"],
  "endow": ["부여하다"],
  "gratify": ["만족시키다"],
  "intricate": ["복잡한"],
  "intrude": ["침입하다", "끼어들다"],
  "mandate": ["명령", "위임하다"],
  "monotonous": ["단조로운"],
  "homogeneous": ["동질의"],
  "conspicuous": ["눈에 띄는"],
  "notation": ["표기법"],
  "pitfall": ["함정"],
  "delude": ["속이다", "착각하게 하다"],
  "propel": ["추진하다"],
  "replicate": ["복제하다", "반복하다"],
  "scrutiny": ["면밀한 조사"],
  "fallacy": ["오류", "허위 논법"],
  "retrospect": ["회고", "회상"],
  "static": ["정적인", "정전기의"],
  "heredity": ["유전"],
  "generic": ["일반적인", "상표 없는"],
  "tranquility": ["평온"],
  "perpetual": ["영구적인", "끊임없는"],
  "rehabilitate": ["재활시키다", "회복시키다"],
  "utilitarian": ["실용적인"],
  "empirical": ["경험적인"],
  "rhetorical": ["수사학의", "반문형의"],
  "zealous": ["열성적인"],
  "indispensable": ["필수적인"],
  "ubiquitous": ["어디에나 있는"],
  "impoverished": ["가난한", "빈곤하게 된"],
  "unanimously": ["만장일치로"],
  "persevere": ["인내하다"],
  "roadblock": ["장애물"],
  "ascribe": ["~의 탓으로 돌리다"],
  "propaganda": ["선전"],
  "latently": ["잠재적으로"],
  "contemporary": ["동시대의", "현대의"],
  "forefather": ["조상"],
  "doctrine": ["교리", "주의"],
  "aviation": ["항공"],
  "aristocrat": ["귀족"],
  "infuse": ["주입하다", "불어넣다"],
  "abound": ["풍부하다"],
  "locomotive": ["기관차"],
  "forthright": ["솔직한"],
  "deduce": ["추론하다"],
  "disprove": ["반증하다"],
  "inaudible": ["들리지 않는"],
  "culinary": ["요리의"],
  "invoke": ["불러내다", "호소하다"],
  "afloat": ["떠 있는", "파산하지 않은"],
  "schema": ["도식", "개요"],
  "capitalism": ["자본주의"],
  "haul": ["끌다", "운반량"],
  "entitlement": ["권리", "자격"],
  "commercialization": ["상업화"],
  "disvalue": ["가치를 깎아내리다", "무가치"],
  "humanitarian": ["인도주의의", "인도주의자"],
  "polarization": ["양극화"],
  "deficit": ["적자", "부족"],
  "sensual": ["관능적인", "감각적인"],
  "ahostof": ["수많은"],
  "irrespective of": ["~와 관계없이"],
  "vulgar": ["저속한"],
  "toddler": ["걸음마를 배우는 아이"],
  "idle": ["게으른", "놀고 있는"],
  "concerted": ["합심한", "공동의"],
  "averse": ["반대하는", "싫어하는"],
  "endorse": ["지지하다", "보증하다"],
  "intelligible": ["이해할 수 있는"],
  "inadvertently": ["무심코", "뜻하지 않게"],
  "excerpt": ["발췌문"],
  "beneficiary": ["수혜자"],
  "transnational": ["국경을 넘는"],
  "iconic": ["상징적인"],
  "staple": ["주요한", "스테이플러"],
  "advisory": ["자문의", "권고의"],
  "airborne": ["공중에 떠 있는"],
  "hallmark": ["특징", "품질 보증 인장"],
  "erroneously": ["잘못하여"],
  "consensus": ["합의"],
  "prerequisite": ["전제 조건"],
  "biosphere": ["생물권"],
  "on the verge of": ["막 ~하려는 참에"],
  "obsolete": ["구식의", "쓸모없게 된"],
  "opaque": ["불투명한", "이해하기 어려운"],
  "mandatory": ["의무적인"],
  "pervasive": ["만연한", "널리 퍼진"],
  "prevalent": ["널리 퍼진"],
  "plentiful": ["풍부한"],
  "ample": ["충분한", "넓은"],
  "prolific": ["다작의", "풍부한"],
  "sterile": ["불임의", "무균의"],
  "productive": ["생산적인"],
  "profitable": ["수익성 있는"],
  "beneficial": ["유익한"],
  "mortal": ["죽을 운명의", "인간"],
  "transient": ["일시적인"],
  "enduring": ["오래 지속되는"],
  "lasting": ["지속적인"],
  "counterfeit": ["위조의", "위조품"],
  "acquired": ["습득한", "후천적인"],
  "intentional": ["의도적인"],
  "accidental": ["우연한"],
  "organized": ["조직된", "정리된"],
  "chaotic": ["혼란스러운"],
  "neat": ["깔끔한"],
  "messy": ["지저분한"],
  "sloppy": ["대충 하는", "지저분한"],
  "meticulous": ["꼼꼼한"],
  "careless": ["부주의한"],
  "negligent": ["태만한"],
  "cautious": ["조심스러운"],
  "prudent": ["신중한"],
  "daring": ["대담한"],
  "courageous": ["용감한"],
  "fearless": ["겁 없는"],
  "valiant": ["용감한"],
  "heroic": ["영웅적인"],
  "ignoble": ["비열한", "비천한"],
  "haughty": ["거만한"],
  "conceited": ["자만하는"],
  "altruistic": ["이타적인"],
  "stingy": ["인색한"],
  "miser": ["구두쇠"],
  "frugal": ["검소한"],
  "extravagant": ["사치스러운"],
  "lavish": ["아낌없이 주는", "사치스러운"],
  "luxurious": ["호화로운"],
  "preach": ["설교하다"],
  "predominate": ["우세하다"],
  "procure": ["조달하다", "얻다"],
  "prosecute": ["기소하다", "수행하다"],
  "purify": ["정화하다"],
  "reap": ["거두다", "수확하다"],
  "recede": ["물러나다"],
  "reckon": ["생각하다", "계산하다"],
  "reconcile": ["화해시키다", "조화시키다"],
  "rectify": ["바로잡다"],
  "redeem": ["되찾다", "보상하다"],
  "reimburse": ["상환하다", "배상하다"],
  "relinquish": ["포기하다", "양도하다"],
  "renounce": ["포기하다", "단념하다"],
  "reproach": ["비난하다", "비난"],
  "resonance": ["반향", "공명"],
  "retaliate": ["보복하다"],
  "retard": ["지연시키다"],
  "revoke": ["철회하다"],
  "salvage": ["구하다", "구조"],
  "scrutinize": ["면밀히 조사하다"],
  "segregate": ["분리하다"],
  "sober": ["술 취하지 않은", "냉정한"],
  "solicit": ["간청하다", "권유하다"],
  "stipulate": ["규정하다"],
  "subsidize": ["보조금을 주다"],
  "summon": ["소환하다", "불러모으다"],
  "synchronize": ["동시에 일어나게 하다"],
  "synthesize": ["종합하다", "합성하다"],
  "tangle": ["얽히다", "얽힘"],
  "testify": ["증언하다"],
  "tilt": ["기울다", "기울이다"],
  "transcend": ["초월하다"],
  "cognitive": ["인지의"],
  "versatile": ["다재다능한"],
  "pragmatic": ["실용적인"],
  "unanimous": ["만장일치의"],
  "anomaly": ["이상", "예외"],
  "inevitable": ["불가피한"],
  "ambivalent": ["양면가치적인", "상반된 감정을 가진"],
  "lucrative": ["수익성이 좋은"],
  "detrimental": ["해로운"],
  "adversary": ["적", "상대"],
  "benevolence": ["자비", "선의"],
  "eloquence": ["웅변", "달변"],
  "frivolous": ["경박한", "하찮은"],
  "perpetuate": ["영속시키다", "지속시키다"],
  "impetuous": ["충동적인"],
  "kinship": ["친족 관계", "유대감"],
  "vibrant": ["활기찬"],
  "critical": ["중요한", "비판적인"],
  "procrastinate": ["미루다"],
  "accordingly": ["그에 따라"],
  "accuracy": ["정확성"],
  "acquisition": ["습득", "획득"],
  "administration": ["관리", "행정"],
  "aggregate": ["총합의", "합계"],
  "allege": ["주장하다"],
  "ambition": ["야망", "포부"],
  "applicable": ["적용 가능한"],
  "assumption": ["가정"],
  "autonomous": ["자율적인"],
  "category": ["범주", "부류"],
  "cohesion": ["결속력", "응집성"],
  "commence": ["시작하다"],
  "comprehensive": ["포괄적인", "종합적인"],
  "constituent": ["구성 요소", "성분"],
  "cumulative": ["누적되는"],
  "demographic": ["인구 통계의"],
  "deter": ["단념시키다", "막다"],
  "diagnosis": ["진단"],
  "diligent": ["부지런한", "성실한"],
  "discrepancy": ["차이", "불일치"],
  "efficacy": ["효능", "유효성"],
  "emission": ["배출", "방출"],
  "enthusiastic": ["열정적인"],
  "evolutionary": ["진화의", "발전의"],
  "expenditure": ["지출"],
  "feasible": ["실행 가능한"],
  "foundation": ["기초", "토대"],
  "guideline": ["지침"],
  "hypothetical": ["가설의", "가상의"],
  "implication": ["함축", "영향"],
  "inequality": ["불평등"],
  "influential": ["영향력 있는"],
  "intervention": ["개입", "중재"],
  "irrelevant": ["관련 없는"],
  "judgment": ["판단"],
  "judiciary": ["사법부"],
  "justification": ["정당화", "이유"],
  "legibility": ["읽기 쉬움", "판독 가능성"],
  "likelihood": ["가능성"],
  "livelihood": ["생계"],
  "modification": ["수정", "변경"],
  "occupation": ["직업", "점유"],
  "opacity": ["불투명함"],
  "opposition": ["반대"],
  "perception": ["인식", "지각"],
  "persuasive": ["설득력 있는"],
  "priority": ["우선순위"],
  "procedure": ["절차"],
  "provision": ["제공", "조항"],
  "proximity": ["가까움", "근접"],
  "recognition": ["인정", "인식"],
  "reference": ["언급", "참고"],
  "reliability": ["신뢰성"],
  "retention": ["유지", "보유"],
  "scholarship": ["장학금", "학문"],
  "stable": ["안정적인"],
  "uncertainty": ["불확실성"],
  "abide": ["준수하다", "견디다"],
  "analytical": ["분석적인"],
  "articulate": ["분명히 표현하다", "분명한"],
  "baseline": ["기준선", "기초 수준"],
  "complementary": ["상호 보완적인"],
  "compliance": ["준수", "따름"],
  "destructive": ["파괴적인"],
  "deviate": ["벗어나다", "일탈하다"],
  "embark": ["착수하다", "탑승하다"],
  "equity": ["공정성", "자기자본"],
  "erratic": ["불규칙한", "종잡을 수 없는"],
  "implicit": ["암시적인", "내포된", "절대적인"],
  "exposure": ["노출", "접촉"],
  "finite": ["한정된"],
  "formidable": ["만만치 않은", "강력한"],
  "impartial": ["공정한", "치우치지 않은"],
  "inclusive": ["포괄적인", "포함하는"],
  "peripheral": ["주변의", "부수적인"],
  "phenomenal": ["경이적인", "놀라운"],
  "qualitative": ["질적인"],
  "quantitative": ["양적인"],
  "refute": ["반박하다"],
  "remainder": ["나머지"],
  "subtlety": ["미묘함"],
  "tentative": ["잠정적인", "망설이는"],
  "thereby": ["그로 인해"],
  "undermine": ["약화시키다"],
  "whereby": ["그에 의해", "그것으로"],
  "moreover": ["게다가", "더욱이"],
  "validate": ["입증하다", "확인하다"]
    }


FILES = {
    "middle": "중등 최종.txt",
    "high": "고등 최종.txt"
}
OUTPUT_FILE = 'worddata.js'
DAILY_NEW_COUNT = 30

def get_meaning(word):
    # 1. 단어를 소문자로 바꾸고 공백 제거해서 찾기
    clean_w = word.lower().strip()
    res = MEANING_DB.get(clean_w)
    
    # 2. 뜻이 존재할 경우
    if res:
        # 뜻이 ["종교"] 처럼 리스트 형식이면 그대로 반환
        if isinstance(res, list):
            return res
        # 뜻이 "종교" 처럼 일반 텍스트면 리스트로 감싸서 반환 (안전장치)
        return [res]
    
    # 3. 뜻이 없을 경우 누락 방지용 텍스트
    return ["뜻 확인 필요"]

def process_file(file_path):
    if not os.path.exists(file_path): return {}
    
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = [line.strip() for line in f if line.strip()]
    
    unique_words = []
    seen = set()
    for w in lines:
        cleaned = clean_word(w) # 교정 로직 적용
        if cleaned not in seen:
            unique_words.append(cleaned)
            seen.add(cleaned)
            
    word_pool = [{"word": w, "meanings": get_meaning(w)} for w in unique_words]
    
    scheduled_data = {}
    idx = 0
    week_num = 1
    
    while idx < len(word_pool):
        week_key = f"week{week_num}"
        scheduled_data[week_key] = {}
        week_words = []
        
        for day in range(1, 6):
            daily_slice = word_pool[idx : idx + DAILY_NEW_COUNT]
            scheduled_data[week_key][str(day)] = daily_slice
            week_words.extend(daily_slice)
            idx += DAILY_NEW_COUNT
            if idx >= len(word_pool): break
            
        mid = len(week_words) // 2
        scheduled_data[week_key]["6"] = {
            "review_parts": [week_words[:mid//2], week_words[mid//2:mid]],
            "test": week_words[:mid]
        }
        scheduled_data[week_key]["7"] = {
            "review_parts": [week_words[mid:mid+(len(week_words)-mid)//2], week_words[mid+(len(week_words)-mid)//2:]],
            "test": week_words[mid:]
        }
        week_num += 1
    return scheduled_data

def main():
    final_data = {}
    for cat, f_name in FILES.items():
        final_data[cat] = process_file(f_name)
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("const wordsData = ")
        json.dump(final_data, f, indent=2, ensure_ascii=False)
        f.write(";")
    print(f"✅ 구조 및 뜻 매핑 완료: {OUTPUT_FILE} 생성됨")

if __name__ == "__main__":
    main()